FROM docker.elastic.co/kibana/kibana:7.2.0

# RUN mkdir -p /opt/config/elasticsearch
# RUN mkdir -p /opt/config/logstash

# COPY config/elasticsearch/update_template.sh /opt/config/elasticsearch
# COPY config/logstash/cases_mapping.json /opt/config/logstash
# COPY config/logstash/flightpax_template.json /opt/config/logstash

# CMD ["/opt/config/elasticsearch/update_template.sh"]