#!/bin/bash
set -eux

wait-for-url() {
    timeout -s TERM 10000 bash -c \
    'while [[ "$(curl -k -s -o /dev/null -L -w ''%{http_code}'' -u elastic:$(cat /bootstrap-password/elastic-bootstrap-password) https://localhost:5601/login)" != "200" ]];\
    do echo "Waiting for kibana" && sleep 2;\
    done'
    echo "OK!"
    curl -k -u elastic:$(cat /bootstrap-password/elastic-bootstrap-password) -X POST -H "Content-Type: application/json" -H "kbn-xsrf: true" "https://localhost:5601/api/telemetry/v2/optIn" -d '{"enabled":false}'
    curl -k -u elastic:$(cat /bootstrap-password/elastic-bootstrap-password) -X POST -H "Content-Type: application/json" -H "kbn-xsrf: true" "https://localhost:5601/api/kibana/dashboards/import?force=true" -d @/usr/share/kibana/kibana.default-dashboard.json
    curl -k -u elastic:$(cat /bootstrap-password/elastic-bootstrap-password) -X POST -H "Content-Type: application/json" -H "kbn-xsrf: true" "https://localhost:5601/api/kibana/settings/defaultIndex" -d '{"value": "96df0890-2ba8-11e9-a5e4-2bbcf61c6cb1"}'
}

wait-for-url