FROM adoptopenjdk/maven-openjdk8 as build-db

COPY ./ /gtas-parent/
WORKDIR /gtas-parent/gtas-commons
RUN mvn clean install -Dmaven.test.skip=true

RUN mvn hibernate:create -Dhibernate.schema.execute=false

FROM mariadb:10.4

COPY --from=build-db /gtas-parent/gtas-commons/target/create.sql /docker-entrypoint-initdb.d/b-create.sql
COPY ./gtas-commons/secrets/init/ /docker-entrypoint-initdb.d/