networks:
  GTAS_webapp-network:
    attachable: true
    driver: overlay
secrets:
  elastic_bootstrap_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elastic_bootstrap_password.txt
  elastic_ca:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elastic-ca.crt
  elastic_cert:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elasticsearch-node1.crt
  elastic_key:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elasticsearch-node1.key
  elastic_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elastic_password.txt
  elasticsearch_ca:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elastic-ca.crt
  elasticsearch_instance_crt:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elasticsearch-node1.crt
  elasticsearch_instance_key:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elasticsearch-node1.key
  elasticsearch_kibana_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elasticsearch_kibana_password.txt
  elasticsearch_kibana_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/elasticsearch_kibana_user.txt
  etl_neo4j_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/etl_neo4j_password.txt
  etl_neo4j_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/etl_neo4j_user.txt
  kibana_crt:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/kibana.crt
  kibana_key:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/kibana.key
  logstash_keystore_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/logstash_keystore_password.txt
  mysql_etl_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_etl_password.txt
  mysql_etl_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_etl_user.txt
  mysql_healthcheck_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_healthcheck_password.txt
  mysql_healthcheck_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_healthcheck_user.txt
  mysql_logstash_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_logstash_password.txt
  mysql_logstash_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_logstash_user.txt
  mysql_processor_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_processor_password.txt
  mysql_processor_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_processor_user.txt
  mysql_root_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_root_password.txt
  mysql_webapp_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_webapp_password.txt
  mysql_webapp_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/mysql_webapp_user.txt
  webapp_neo4j_password:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/webapp_neo4j_password.txt
  webapp_neo4j_user:
    file: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/gtas-commons/secrets/webapp_neo4j_user.txt
services:
  activemq:
    container_name: activemq
    deploy:
      placement:
        constraints:
        - node.hostname == gtas-node
    image: rmohr/activemq
    networks:
      GTAS_webapp-network: {}
    restart: always
  elasticsearch:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/scripts/elastic
      dockerfile: install/docker/elasticsearch/Dockerfile
    container_name: elasticsearch
    deploy:
      placement:
        constraints:
        - node.hostname == elk-node
    image: wcogtas/elasticsearch:1.0.0
    networks:
      GTAS_webapp-network: {}
    ports:
    - published: 9200
      target: 9200
    - published: 9300
      target: 9300
    restart: always
    secrets:
    - source: elasticsearch_ca
      target: /usr/share/elasticsearch/config/certs/elasticsearch/elastic-ca.crt
    - source: elasticsearch_instance_crt
      target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-node1.crt
    - source: elasticsearch_instance_key
      target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-node1.key
    volumes:
    - elasticsearch_conf:/usr/share/elasticsearch/config:rw
    - es-data:/usr/share/elasticsearch/data:rw
  elk-setup:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/scripts/elastic
      dockerfile: ./install/docker/elk-setup/Dockerfile
    container_name: elk-setup
    deploy:
      placement:
        constraints:
        - node.hostname == elk-node
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      KIBANA_HOST: kibana
    image: wcogtas/elk-setup:1.0.0
    networks:
      GTAS_webapp-network: {}
    secrets:
    - source: elastic_bootstrap_password
    - source: elastic_password
    - source: elasticsearch_kibana_password
    - source: elasticsearch_kibana_user
    - source: logstash_keystore_password
    - source: mysql_logstash_password
    - source: mysql_logstash_user
    volumes:
    - elasticsearch_conf:/elasticsearch-conf:rw
    - kibana_conf:/kibana-conf:rw
    - logstash_conf:/logstash-conf:rw
  etl-job:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS
      dockerfile: ./gtas-neo4j-etl/etl_job.Dockerfile
    container_name: etl-job
    depends_on:
    - neo4j
    deploy:
      placement:
        constraints:
        - node.hostname == neo4j-node
    environment:
      DB_HOSTNAME: mariadb
      NEO4J_HOSTNAME: neo4j
    image: wcogtas/neo4j-etl-job:1.0.0
    networks:
      GTAS_webapp-network: {}
    restart: always
    secrets:
    - source: etl_neo4j_password
    - source: etl_neo4j_user
    - source: mysql_etl_password
    - source: mysql_etl_user
  gtas-scheduler:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS
      dockerfile: gtas-parent/gtas-job-scheduler-war/Dockerfile
    container_name: gtas-scheduler
    depends_on:
    - activemq
    deploy:
      placement:
        constraints:
        - node.hostname == gtas-node
    environment:
      ACTIVEMQ_HOST: activemq
      DB_HOST: mariadb
      KIBANA_HOST: kibana
      NEO4J_HOST: neo4j
    image: wcogtas/gtas-scheduler:1.0.0
    networks:
      GTAS_webapp-network: {}
    restart: always
    secrets:
    - source: mysql_processor_password
    - source: mysql_processor_user
    - source: webapp_neo4j_password
    - source: webapp_neo4j_user
    volumes:
    - consistency: consistent
      source: /mnt
      target: /usr/local/gtas-data
      type: bind
    - scheduler-logs:/usr/local/tomcat/logs:rw
  http-proxy:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/docker-resources
      dockerfile: proxy.Dockerfile
    container_name: http-proxy
    deploy:
      placement:
        constraints:
        - node.hostname == gtas-node
    image: wcogtas/http-proxy:1.0.0
    networks:
      GTAS_webapp-network: {}
    ports:
    - published: 80
      target: 80
    restart: always
    secrets:
    - source: elastic_bootstrap_password
  kibana:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/scripts/elastic
      dockerfile: install/docker/kibana/Dockerfile
    container_name: kibana
    depends_on:
    - elasticsearch
    deploy:
      placement:
        constraints:
        - node.hostname == elk-node
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
    image: wcogtas/kibana:1.0.0
    networks:
      GTAS_webapp-network: {}
    ports:
    - published: 5601
      target: 5601
    restart: always
    secrets:
    - source: elasticsearch_ca
      target: /etc/kibana/config/ca.crt
    - source: kibana_crt
      target: /etc/kibana/config/kibana.crt
    - source: kibana_key
      target: /etc/kibana/config/kibana.key
    volumes:
    - kibana_conf:/usr/share/kibana/data:rw
  logstash:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent/scripts/elastic
      dockerfile: ./install/docker/logstash/Dockerfile
    container_name: logstash
    depends_on:
    - elasticsearch
    deploy:
      placement:
        constraints:
        - node.hostname == elk-node
    environment:
      ELASTIC_HOST: https://elasticsearch
      LOGSTASH_KEYSTORE_PASS: admin123
      MARIADB_HOST: mariadb
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: elasticsearch
    image: wcogtas/logstash:1.0.0
    networks:
      GTAS_webapp-network: {}
    restart: always
    secrets:
    - source: elasticsearch_ca
    volumes:
    - logstash_conf:/usr/share/logstash/config:rw
  mariadb:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent
      dockerfile: Dockerfile-mariadb
    container_name: mariadb
    deploy:
      placement:
        constraints:
        - node.hostname == gtas-node
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    image: wcogtas/mariadb:1.0.0
    networks:
      GTAS_webapp-network: {}
    ports:
    - published: 3306
      target: 3306
    restart: always
    secrets:
    - source: mysql_etl_password
    - source: mysql_etl_user
    - source: mysql_healthcheck_password
    - source: mysql_healthcheck_user
    - source: mysql_logstash_password
    - source: mysql_logstash_user
    - source: mysql_processor_password
    - source: mysql_processor_user
    - source: mysql_root_password
    - source: mysql_webapp_password
    - source: mysql_webapp_user
    volumes:
    - db-data:/var/lib/mysql:rw
  neo4j:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS
      dockerfile: ./gtas-neo4j-etl/neo4j.Dockerfile
    container_name: neo4j
    deploy:
      placement:
        constraints:
        - node.hostname == neo4j-node
    image: wcogtas/neo4j:1.0.0
    networks:
      GTAS_webapp-network: {}
    ports:
    - published: 7474
      target: 7474
    - published: 7687
      target: 7687
    restart: always
  web-app:
    build:
      context: /Users/simbamarufu/Documents/GitHub/GTAS/gtas-parent
    container_name: web-app
    depends_on:
    - mariadb
    deploy:
      placement:
        constraints:
        - node.hostname == gtas-node
    environment:
      ACTIVEMQ_HOST: activemq
      DB_HOST: mariadb
      ELASTICSEARCH: elasticsearch
      KIBANA_HOST: kibana
      NEO4J_HOST: neo4j
      PROXY_HOST: httpproxy
    image: wcogtas/web-app:1.0.0
    networks:
      GTAS_webapp-network: {}
    ports:
    - published: 8080
      target: 8080
    restart: always
    secrets:
    - source: elastic_bootstrap_password
    - source: elastic_ca
      target: /usr/local/tomcat/conf/elastic-ca.crt
    - source: elastic_cert
      target: /usr/local/tomcat/conf/elasticsearch-node1.crt
    - source: elastic_key
      target: /usr/local/tomcat/conf/elasticsearch-node1.key
    - source: mysql_webapp_password
    - source: mysql_webapp_user
    - source: webapp_neo4j_password
    - source: webapp_neo4j_user
    volumes:
    - m2:/root/.m2:rw
    - scheduler-logs:/scheduler-logs:rw
version: '3.7'
volumes:
  db-data: {}
  elasticsearch_conf: {}
  es-data: {}
  kibana_conf: {}
  logstash_conf: {}
  m2: {}
  scheduler-logs: {}

