/*
* Default rules for the GTAS system.
* TODO: create Meta Rules and Rule Flow here - AB.
*/
package gov.gtas;

import gov.gtas.model.Flight;
import gov.gtas.model.FlightPax;
import gov.gtas.model.Passenger
import gov.gtas.bo.RuleHitDetail;

global java.util.List resultList

rule "R1 - Passenger Bag Weight is 0"
    dialect "java"

    when
        fp:FlightPax( fp.getBagWeight == 0)
    then
    resultList.add(new RuleHitDetail(1L, "hitType", fp.getPassenger(), "cause"));

end

rule "R2 - List Passengers"
    dialect "java"
    when

    fp:FlightPax()
    p:Passenger(id == fp.getPassenger().getId() && embarkation.equals("Timbuktu"))
    f:Flight(id == fp.getFlight().getId())

    then

    resultList.add(new RuleHitDetail(2L, "hitType", p, "cause"));

end
