export DB_USERNAME=$(cat ${MYSQL_USER_PATH})
export DB_PASSWORD=$(cat ${MYSQL_PASSWORD_PATH})
export NEO4J_USERNAME=$(cat ${NEO4J_USER_PATH})
export NEO4J_PASSWORD=$(cat ${NEO4J_PASSWORD_PATH})
export ELASTIC_USERNAME=elastic
export ELASTIC_PASSWORD=$(cat ${BOOTSTRAP_PATH})
export ELASTICSEARCH_HOST=elasticsearch
