DELETE FROM app_configuration WHERE VAL = 'INTERPOL_SNS_NOTIFICATION_ARN';
DELETE FROM app_configuration WHERE VAL = 'ENABLE_INTERPOL_HIT_NOTIFICATION';
DELETE FROM app_configuration WHERE VAL = 'INTERPOL_WATCHLIST_ID';
DELETE FROM app_configuration WHERE VAL = 'INTERPOL_SNS_NOTIFICATION_SUBJECT';