version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    networks: 
      - gtas_default

  elasticsearch:
    image: elasticsearch:2.3.2
    container_name: elastic
    networks: 
      - gtas_default
    ports: 
      - 9300:9300
      - 9200:9200
    healthcheck:
      test: curl --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  activemq:
    image: rmohr/activemq
    container_name: activemq
    networks: 
      - gtas_default

  mariahost:
    image: sanandreas/gtas_mariadb:v4
    container_name: mariahost
    networks: 
      - gtas_default
  
  tomcatgtas:
    image: sanandreas/gtas_tomcat:v4
    container_name: tomcat
    networks: 
      - gtas_default
    ports: 
      - 8080:8080
    environment:
      LOCAL_DRIVE_MAPPING_INPUT: ${LOCAL_DRIVE_MAPPING_INPUT}
      LOCAL_DRIVE_MAPPING_OUTPUT: ${LOCAL_DRIVE_MAPPING_OUTPUT}
    volumes:
      - ${LOCAL_DRIVE_MAPPING_INPUT}:/usr/local/input:rw
      - ${LOCAL_DRIVE_MAPPING_OUTPUT}:/usr/local/output:rw

networks:
  gtas_default:
