package gov.gtas.services;

import gov.gtas.enumtype.HitTypeEnum;
import gov.gtas.model.HitMaker;
import gov.gtas.model.ManualHit;
import gov.gtas.model.PendingHitDetails;
import gov.gtas.repository.HitMakerRepository;
import gov.gtas.repository.PendingHitDetailRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;
import java.util.Set;

@Service
public class PendingHitDetailsServiceImpl implements PendingHitDetailsService {

    @Autowired
    PendingHitDetailRepository phr;

    @Autowired
    HitMakerRepository hmr;

    //For generation of manual hits.
    @Override
    @Transactional
    public void createPendingHitDetail(Long paxId, Long flightId, String userId){
        PendingHitDetails phd = new PendingHitDetails();

        ManualHit mh = new ManualHit();
        mh.setDescription("Manual Hit Generated On Passenger Detail Page");
        hmr.save(mh);

        phd.setTitle("Manual PVL Generation");
        phd.setDescription("Manual Hit Generated By" + userId);

        phd.setHitEnum(HitTypeEnum.MANUAL_HIT);
        phd.setHitType(HitTypeEnum.MANUAL_HIT.toString());
        phd.setPercentage(1);
        //Manual hit generation, no rule conditions.
        phd.setRuleConditions("");
        phd.setPassengerId(paxId);
        phd.setFlightId(flightId);

        phd.setCreatedDate(new Date());
        phd.setCreatedBy(userId);

        phd.setHitMaker(mh);
        phd.setHitMakerId(mh.getId());

        phr.save(phd);
    };

    @Override
    public void saveAllPendingHitDetails(Set<PendingHitDetails> phdSet){
        phr.saveAll(phdSet);
    };

}
