insert into carrier(name, iata, icao) values ('40-Mile Air, Ltd.', 'Q5', 'MLA');
insert into carrier(name, iata, icao) values ('ABC Aerolineas S.A. de C.V.', '4O', 'AIJ');
insert into carrier(name, iata, icao) values ('ABSA  -  Aerolinhas Brasileiras S.A.', 'M3', 'TUS');
insert into carrier(name, iata, icao) values ('ABX Air, Inc.', 'GB', '');
insert into carrier(name, iata, icao) values ('ACT Havayollari A.S.', '9T', '');
insert into carrier(name, iata, icao) values ('AEROFLOT-NORD', '5N', 'AUL');
insert into carrier(name, iata, icao) values ('AHK Air Hong Kong Limited', 'LD', 'AHK');
insert into carrier(name, iata, icao) values ('ANA & JP Express Co. ltd', '9N', 'AJV');
insert into carrier(name, iata, icao) values ('AVIACSA-Consorcio Aviaxsa, S.A. de C.V.', '6A', 'CHP');
insert into carrier(name, iata, icao) values ('AVIATECA, S.A.', 'GU', '');
insert into carrier(name, iata, icao) values ('Adria Airways - The Airline of Slovenia', 'JP', 'ADR');
insert into carrier(name, iata, icao) values ('Aegean Airlines S.A.', 'A3', 'AEE');
insert into carrier(name, iata, icao) values ('Aeko Kula, Inc. DBA Aloha Air Cargo', 'KH', '');
insert into carrier(name, iata, icao) values ('Aer Arann Express', 'RE', 'REA');
insert into carrier(name, iata, icao) values ('Aer Lingus Limited', 'EI', 'EIN');
insert into carrier(name, iata, icao) values ('Aero 2000 S.A.', '4M', '');
insert into carrier(name, iata, icao) values ('Aero Airlines A.S.', 'EE', '');
insert into carrier(name, iata, icao) values ('Aero Contractors Nigeria Limited', 'AJ', 'NIG');
insert into carrier(name, iata, icao) values ('Aero Express del Ecuador  - Trans AM', '7T', '');
insert into carrier(name, iata, icao) values ('Aero Micronesia Inc.', '', 'MGE');
insert into carrier(name, iata, icao) values ('Aero Mongolia', 'M0', 'MNG');
insert into carrier(name, iata, icao) values ('Aero Regional Paraguaya S.A.', 'P7', '');
insert into carrier(name, iata, icao) values ('Aero Republica S.A.', 'P5', 'RPB');
insert into carrier(name, iata, icao) values ('Aero V.I.P. Ltda', '', 'QCL');
insert into carrier(name, iata, icao) values ('Aerocaribbean S.A.', '7L', 'CRN');
insert into carrier(name, iata, icao) values ('Aerocomercial Oriente Norte Ltda', 'A4', '');
insert into carrier(name, iata, icao) values ('Aeroflot - Cargo', 'SU', 'RCF');
insert into carrier(name, iata, icao) values ('Aeroflot Russian Airlines', 'SU', 'AFL');
insert into carrier(name, iata, icao) values ('Aeroflot-Don', 'D9', 'DNV');
insert into carrier(name, iata, icao) values ('Aerogaviota  S.A.', 'KG', '');
insert into carrier(name, iata, icao) values ('Aerolinea Principal Chile S.A.', '5P', 'PCP');
insert into carrier(name, iata, icao) values ('Aerolineas Argentinas', 'AR', 'ARG');
insert into carrier(name, iata, icao) values ('Aerolineas Austral Chile S.A.', '3I', '');
insert into carrier(name, iata, icao) values ('Aerolineas Galapagos S.A. Aerogal', '2K', 'GLG');
insert into carrier(name, iata, icao) values ('Aerolineas Regionales, S.A. de C.V', 'F2', 'RCQ');
insert into carrier(name, iata, icao) values ('Aerolineas de Baleares AeBal', 'DF', 'ABH');
insert into carrier(name, iata, icao) values ('Aerolitoral S.A. de C.V.', '5D', 'SLI');
insert into carrier(name, iata, icao) values ('Aeromexico', 'AM', 'AMX');
insert into carrier(name, iata, icao) values ('Aeroperlas', 'WL', '');
insert into carrier(name, iata, icao) values ('Aeropostal Alas de Venezuela C.A.', 'VH', '');
insert into carrier(name, iata, icao) values ('Aerosur Paraguay S.A.', 'PQ', '');
insert into carrier(name, iata, icao) values ('Aerosvit Airlines', 'VV', 'AEW');
insert into carrier(name, iata, icao) values ('Aerosyncro Aviation AB', '6I', 'IBZ');
insert into carrier(name, iata, icao) values ('Aerotransporte de Carga Union, S.A. de C', '6R', 'TNO');
insert into carrier(name, iata, icao) values ('Aerotransportes Mas de Carga', 'M7', 'MAA');
insert into carrier(name, iata, icao) values ('Aerovias Caribe S.A. de C.V.', 'QA', 'CBE');
insert into carrier(name, iata, icao) values ('Aerovias del Continente Americano S.A', 'AV', 'AVA');
insert into carrier(name, iata, icao) values ('Africa West', 'FK', '');
insert into carrier(name, iata, icao) values ('African International Airways', '', 'AIN');
insert into carrier(name, iata, icao) values ('Afriqiyah Airways', '8U', 'AAW');
insert into carrier(name, iata, icao) values ('Aigle Azur', 'ZI', 'AAF');
insert into carrier(name, iata, icao) values ('Air Algerie', 'AH', 'DAH');
insert into carrier(name, iata, icao) values ('Air Almaty JSC', 'K7', 'LMY');
insert into carrier(name, iata, icao) values ('Air Arabia', 'G9', '');
insert into carrier(name, iata, icao) values ('Air Armenia', 'QN', '');
insert into carrier(name, iata, icao) values ('Air Astana', 'KC', 'KZR');
insert into carrier(name, iata, icao) values ('Air Atlanta Icelandic', 'CC', 'ABD');
insert into carrier(name, iata, icao) values ('Air Austral', 'UU', 'REU');
insert into carrier(name, iata, icao) values ('Air Bagan Ltd.', 'W9', '');
insert into carrier(name, iata, icao) values ('Air Baltic Corporation SIA', 'BT', '');
insert into carrier(name, iata, icao) values ('Air Bashkortostan Ltd.', 'ZU', 'BBT');
insert into carrier(name, iata, icao) values ('Air Bee S.p.A', 'BM', 'OBE');
insert into carrier(name, iata, icao) values ('Air Bissau International Lda', 'YL', 'BSA');
insert into carrier(name, iata, icao) values ('Air Botswana Corporation', 'BP', 'BOT');
insert into carrier(name, iata, icao) values ('Air Busan', 'BX', '');
insert into carrier(name, iata, icao) values ('Air Caledonie', 'TY', 'TPC');
insert into carrier(name, iata, icao) values ('Air Caledonie International', 'SB', 'ACI');
insert into carrier(name, iata, icao) values ('Air Canada', 'AC', 'ACA');
insert into carrier(name, iata, icao) values ('Air Canada Jazz', 'QK', 'JZA');
insert into carrier(name, iata, icao) values ('Air Caraibes', 'TX', 'FWI');
insert into carrier(name, iata, icao) values ('Air Cargo Carriers, Inc.', '2Q', 'SNC');
insert into carrier(name, iata, icao) values ('Air Charter Express Limited', '', 'ACE');
insert into carrier(name, iata, icao) values ('Air China Cargo', 'CA', '');
insert into carrier(name, iata, icao) values ('Air Comet S.A.', 'A7', 'MPD');
insert into carrier(name, iata, icao) values ('Air Company ITEK-AIR Ltd.', 'GI', 'IKA');
insert into carrier(name, iata, icao) values ('Air Company Somon Air', '4J', '');
insert into carrier(name, iata, icao) values ('Air Continental Africa', 'TI', '');
insert into carrier(name, iata, icao) values ('Air Contractors (UK) Limited', 'AG', 'ABR');
insert into carrier(name, iata, icao) values ('Air Creebec (1994) Inc.', 'YN', 'CRQ');
insert into carrier(name, iata, icao) values ('Air Dolomiti S.p.A.', 'EN', 'DLA');
insert into carrier(name, iata, icao) values ('Air Dominicana S.A.', '6D', '');
insert into carrier(name, iata, icao) values ('Air Eagle (Pvt) Ltd.', '', 'SEE');
insert into carrier(name, iata, icao) values ('Air Ecuador Airecu S.A.', 'N5', '');
insert into carrier(name, iata, icao) values ('Air Europa Lineas Aereas, S.A.', 'UX', 'AEA');
insert into carrier(name, iata, icao) values ('Air Fiji Ltd.', 'PC', 'FAJ');
insert into carrier(name, iata, icao) values ('Air Finland Ltd.', 'OF', '');
insert into carrier(name, iata, icao) values ('Air France', 'AF', 'AFR');
insert into carrier(name, iata, icao) values ('Air Go Airlines S.A.', '4A', '');
insert into carrier(name, iata, icao) values ('Air Greenland A/S', 'GL', 'GRL');
insert into carrier(name, iata, icao) values ('Air Iceland (Flugfelag Islands)', 'NY', 'FXI');
insert into carrier(name, iata, icao) values ('Air India Charters Limited', 'IX', '');
insert into carrier(name, iata, icao) values ('Air Inuit Ltd/Ltee', '3H', 'AIE');
insert into carrier(name, iata, icao) values ('Air Italy S.p.A.', 'I9', '');
insert into carrier(name, iata, icao) values ('Air Jamaica', 'JM', 'AJM');
insert into carrier(name, iata, icao) values ('Air Koryo', 'JS', 'KOR');
insert into carrier(name, iata, icao) values ('Air Kurfa', '7F', 'KAV');
insert into carrier(name, iata, icao) values ('Air Lines of Kuban', 'GW', 'KIL');
insert into carrier(name, iata, icao) values ('Air Logistics L.L.C. d/b/a', 'L9', 'ALG');
insert into carrier(name, iata, icao) values ('Air Macau Company Limited', 'NX', 'AMU');
insert into carrier(name, iata, icao) values ('Air Madagascar', 'MD', 'MDG');
insert into carrier(name, iata, icao) values ('Air Malawi Limited', 'QM', 'AML');
insert into carrier(name, iata, icao) values ('Air Malta p.l.c.', 'KM', 'AMC');
insert into carrier(name, iata, icao) values ('Air Marshall Islands, Inc.', 'CW', 'MRS');
insert into carrier(name, iata, icao) values ('Air Mascareignes Ltd.', 'MV', '');
insert into carrier(name, iata, icao) values ('Air Mauritius', 'MK', 'MAU');
insert into carrier(name, iata, icao) values ('Air Midwest', 'ZV', 'AMW');
insert into carrier(name, iata, icao) values ('Air Mobility Command', 'MC', '');
insert into carrier(name, iata, icao) values ('Air Moldova', '9U', 'MLD');
insert into carrier(name, iata, icao) values ('Air Namibia', 'SW', 'NMB');
insert into carrier(name, iata, icao) values ('Air Nepal International Pvt. Ltd.', 'XN', 'NPL');
insert into carrier(name, iata, icao) values ('Air New Zealand Limited', 'NZ', 'ANZ');
insert into carrier(name, iata, icao) values ('Air Next Co., Ltd.', '7A', 'NXA');
insert into carrier(name, iata, icao) values ('Air Nippon Co. Ltd.', 'EL', 'ANK');
insert into carrier(name, iata, icao) values ('Air Niugini Pty Limited', 'PX', 'ANG');
insert into carrier(name, iata, icao) values ('Air North Charter and Trainung Ltd.', '4N', '');
insert into carrier(name, iata, icao) values ('Air Nostrum L.A.M.S.A.', 'YW', 'ANE');
insert into carrier(name, iata, icao) values ('Air One', 'AP', 'ADH');
insert into carrier(name, iata, icao) values ('Air Pacific Ltd.', 'FJ', 'FJI');
insert into carrier(name, iata, icao) values ('Air Philippines Corporation', '2P', 'GAP');
insert into carrier(name, iata, icao) values ('Air Saint  Pierre', 'PJ', '');
insert into carrier(name, iata, icao) values ('Air Senegal International', 'V7', 'SNG');
insert into carrier(name, iata, icao) values ('Air Seychelles Limited', 'HM', 'SEY');
insert into carrier(name, iata, icao) values ('Air Sinai', '4D', 'ASD');
insert into carrier(name, iata, icao) values ('Air Speed Up', 'VP', '');
insert into carrier(name, iata, icao) values ('Air Sylhet AG', 'SL', 'SHR');
insert into carrier(name, iata, icao) values ('Air Tahiti', 'VT', 'VTA');
insert into carrier(name, iata, icao) values ('Air Tahiti Nui', 'TN', 'THT');
insert into carrier(name, iata, icao) values ('Air Tanzania Company Ltd.', 'TC', 'ATC');
insert into carrier(name, iata, icao) values ('Air Tindi Ltd.', '8T', '');
insert into carrier(name, iata, icao) values ('Air Transat', 'TS', 'TSC');
insert into carrier(name, iata, icao) values ('Air Transport International Ltd', '8C', '');
insert into carrier(name, iata, icao) values ('Air Urga', '3N', 'URG');
insert into carrier(name, iata, icao) values ('Air Vanuatu (Operations) Limited', 'NF', 'AVN');
insert into carrier(name, iata, icao) values ('Air Via Ltd.', 'VL', 'VIM');
insert into carrier(name, iata, icao) values ('Air Wisconsin Airlines Corporation', 'ZW', 'AWI');
insert into carrier(name, iata, icao) values ('Air Zimbabwe (Pvt) Ltd.', 'UM', 'AZW');
insert into carrier(name, iata, icao) values ('AirBridgeCargo Airlines Limited', 'RU', '');
insert into carrier(name, iata, icao) values ('AirKenya Express Limited', 'P2', 'XAK');
insert into carrier(name, iata, icao) values ('AirTran Airways, Inc.', 'FL', '');
insert into carrier(name, iata, icao) values ('AirX Limited dba Blue Islands', 'SI', 'BCI');
insert into carrier(name, iata, icao) values ('Airasia Sdn Bhd.', 'AK', 'AXM');
insert into carrier(name, iata, icao) values ('Airasia X Sdn. Bhd.', 'D7', '');
insert into carrier(name, iata, icao) values ('Airbus Transport International', '4Y', '');
insert into carrier(name, iata, icao) values ('Aircompany "Esen Air"', 'K9', 'ESD');
insert into carrier(name, iata, icao) values ('Aircompany "Kyrgyzstan"', 'QH', 'LYN');
insert into carrier(name, iata, icao) values ('Aircompany Asia Wings JSC', 'Y5', 'AWA');
insert into carrier(name, iata, icao) values ('Aircompany Polet', 'YQ', '');
insert into carrier(name, iata, icao) values ('Airlines of Papua New Guinea Limited', 'CG', '');
insert into carrier(name, iata, icao) values ('Airmax S.A.', 'M8', '');
insert into carrier(name, iata, icao) values ('Aklak Inc.', '6L', 'AKK');
insert into carrier(name, iata, icao) values ('Al Rais Cargo Agencies L.L.C.', '', 'HJT');
insert into carrier(name, iata, icao) values ('Alajnihah For Air Transport', '2T', 'ANH');
insert into carrier(name, iata, icao) values ('Alas Del Sur S.R.L', 'D4', 'ASC');
insert into carrier(name, iata, icao) values ('Alaska Airlines Inc.', 'AS', 'ASA');
insert into carrier(name, iata, icao) values ('Alaska Central Express', 'KO', 'AER');
insert into carrier(name, iata, icao) values ('Albanian Airlines MAK S.H.P.K.', 'LV', 'LBC');
insert into carrier(name, iata, icao) values ('Alitalia-Compagnia Aerea Italiana S.p.A', 'AZ', 'AZA');
insert into carrier(name, iata, icao) values ('All Nippon Airways Co. Ltd.', 'NH', 'ANA');
insert into carrier(name, iata, icao) values ('Alliance Air', 'CD', 'LLR');
insert into carrier(name, iata, icao) values ('Allied Air Ltd.', '4W', 'AJK');
insert into carrier(name, iata, icao) values ('Alpine Aviation Inc.', '5A', 'AIP');
insert into carrier(name, iata, icao) values ('Amaszonas S.A.', 'Z8', '');
insert into carrier(name, iata, icao) values ('American Airlines Inc.', 'AA', 'AAL');
insert into carrier(name, iata, icao) values ('Ameriflight, LLC', 'A8', 'AMF');
insert into carrier(name, iata, icao) values ('Amerijet International Inc.', 'M6', 'AJT');
insert into carrier(name, iata, icao) values ('Amiri Flight', 'MO', 'AUH');
insert into carrier(name, iata, icao) values ('Andes Lineas Aereas S.A.', 'OY', '');
insert into carrier(name, iata, icao) values ('Angkor Airways Corporation', 'G6', 'AKW');
insert into carrier(name, iata, icao) values ('Antrak Air Limited', 'O4', '');
insert into carrier(name, iata, icao) values ('Arctic Circle Air Service Inc.', '5F', 'CIR');
insert into carrier(name, iata, icao) values ('Arctic Transportation Services, Inc.', '7S', '');
insert into carrier(name, iata, icao) values ('Ariana Afghan Airlines', 'FG', 'AFG');
insert into carrier(name, iata, icao) values ('Arik Niger', 'Q9', '');
insert into carrier(name, iata, icao) values ('Arkia - Israeli Airlines Ltd', 'IZ', 'AIZ');
insert into carrier(name, iata, icao) values ('Armavia', 'U8', '');
insert into carrier(name, iata, icao) values ('Arrow Air Inc.', 'JW', 'APW');
insert into carrier(name, iata, icao) values ('Arrow Panama, S.A.', '8A', '');
insert into carrier(name, iata, icao) values ('Asia Alpha Airways', 'OD', 'SAL');
insert into carrier(name, iata, icao) values ('Asiana Airlines Inc.', 'OZ', 'AAR');
insert into carrier(name, iata, icao) values ('Askari Aviation (PVT) Ltd.', '4K', '');
insert into carrier(name, iata, icao) values ('Astar Air Cargo', 'ER', 'DHL');
insert into carrier(name, iata, icao) values ('Astraeus Ltd.', '5W', 'AEU');
insert into carrier(name, iata, icao) values ('Astral Aviation Ltd.', '8V', '');
insert into carrier(name, iata, icao) values ('Atlant-Soyuz', '7B', 'AYZ');
insert into carrier(name, iata, icao) values ('Atlantic Airways Faroe Islands', 'RC', 'FLI');
insert into carrier(name, iata, icao) values ('Atlantic Southeast Airlines, Inc.', 'EV', 'ACY');
insert into carrier(name, iata, icao) values ('Atlas Air, Inc.', '5Y', '');
insert into carrier(name, iata, icao) values ('Atlasjet Airlines Inc.', 'KK', 'KKK');
insert into carrier(name, iata, icao) values ('Atyrau  Aue Joly', 'IP', 'JOL');
insert into carrier(name, iata, icao) values ('Augsburg Airways GmbH & Co. KG', 'IQ', 'AUB');
insert into carrier(name, iata, icao) values ('Aurigny Air Services Limited', 'GR', 'AUR');
insert into carrier(name, iata, icao) values ('Australian Air Express Pty. Ltd.', 'XM', 'XME');
insert into carrier(name, iata, icao) values ('Austrian Airlines, Osterreichische', 'OS', 'AUA');
insert into carrier(name, iata, icao) values ('Ave.com', '2E', 'PHW');
insert into carrier(name, iata, icao) values ('Aviacon Zitotrans Air Company JSC', 'ZR', '');
insert into carrier(name, iata, icao) values ('Aviaenergo', '7U', '');
insert into carrier(name, iata, icao) values ('Aviastar-TU Co.  Aviacompany', '4B', 'TUP');
insert into carrier(name, iata, icao) values ('Aviation Services, Ltd.', 'FP', 'FRE');
insert into carrier(name, iata, icao) values ('Aviation Starlink Inc.', 'Q4', '');
insert into carrier(name, iata, icao) values ('Avient Aviation (PVT) Limited', 'Z3', 'SMJ');
insert into carrier(name, iata, icao) values ('Avient Cameroon S.A.', 'HC', 'AVC');
insert into carrier(name, iata, icao) values ('Aviones de Oriente C.A. (AVIOR)', '9V', 'ROI');
insert into carrier(name, iata, icao) values ('Azerbaijan Hava Yollary', 'J2', 'AHY');
insert into carrier(name, iata, icao) values ('Aztec Worldwide Airlines Inc.', '7A', '');
insert into carrier(name, iata, icao) values ('Azul Linhas Aereas Brasileiras', 'AD', '');
insert into carrier(name, iata, icao) values ('B & H Airlines', 'JA', '');
insert into carrier(name, iata, icao) values ('BA Cityflyer Limited', 'CJ', 'CFE');
insert into carrier(name, iata, icao) values ('BA European Limited t/a Openskies', 'EC', '');
insert into carrier(name, iata, icao) values ('BIMINI Island Air Inc.', 'B9', '');
insert into carrier(name, iata, icao) values ('Bahamasair Holdings, Limited', 'UP', 'BHS');
insert into carrier(name, iata, icao) values ('Bahrain Air B.S.C.', '2B', '');
insert into carrier(name, iata, icao) values ('Bangkok Airways Co. Ltd.', 'PG', 'BKP');
insert into carrier(name, iata, icao) values ('Bankair Inc.', 'B4', 'BKA');
insert into carrier(name, iata, icao) values ('Baseops International, Inc.', '3Y', 'XBO');
insert into carrier(name, iata, icao) values ('Bearskin Lake air services Ltd.', 'JV', 'BLS');
insert into carrier(name, iata, icao) values ('Belavia', 'B2', 'BRU');
insert into carrier(name, iata, icao) values ('Belle Air Company', 'LZ', 'LBY');
insert into carrier(name, iata, icao) values ('Bellview Airlines Limited', 'B3', 'BLV');
insert into carrier(name, iata, icao) values ('Bemidji Aviation Services, Inc.', 'CH', 'BMJ');
insert into carrier(name, iata, icao) values ('Benin Golf Air S.A.', 'A8', '');
insert into carrier(name, iata, icao) values ('Best Aviation Ltd.', '5Q', 'BEA');
insert into carrier(name, iata, icao) values ('Biman Bangladesh Airlines', 'BG', 'BBC');
insert into carrier(name, iata, icao) values ('Bismillah Airlines', '5Z', '');
insert into carrier(name, iata, icao) values ('Blue Dart Aviation Ltd.', 'BZ', '');
insert into carrier(name, iata, icao) values ('Blue Panorama Airlines S.p.A.', 'BV', 'BPA');
insert into carrier(name, iata, icao) values ('Blue Wings AG', 'QW', 'BWG');
insert into carrier(name, iata, icao) values ('Blue1 Oy', 'KF', 'BLF');
insert into carrier(name, iata, icao) values ('Bluebird Cargo', 'BF', '');
insert into carrier(name, iata, icao) values ('Brendan Airways, LLC', 'U5', 'GWY');
insert into carrier(name, iata, icao) values ('Bringer Air Cargo Taxi Aereo Ltda', 'E6', 'BRC');
insert into carrier(name, iata, icao) values ('Brit Air', 'DB', 'BZH');
insert into carrier(name, iata, icao) values ('British Airways p.l.c.', 'BA', 'BAW');
insert into carrier(name, iata, icao) values ('British Midland Airways Ltd.', 'BD', 'BMA');
insert into carrier(name, iata, icao) values ('Brussels Airlines N.V.', 'SN', 'DAT');
insert into carrier(name, iata, icao) values ('Bulgaria Air', 'FB', 'LZB');
insert into carrier(name, iata, icao) values ('Buraq Air Transport (BRQ)', 'UZ', 'BRQ');
insert into carrier(name, iata, icao) values ('C.A.I. Second S.p.A.', 'VE', 'VLE');
insert into carrier(name, iata, icao) values ('C.A.L. Cargo Airlines Ltd.', '5C', 'ICL');
insert into carrier(name, iata, icao) values ('CEBU Pacific Air', '5J', 'CEB');
insert into carrier(name, iata, icao) values ('CEIBA Intercontinental S.A.', 'C2', '');
insert into carrier(name, iata, icao) values ('CJSC Airline 400', 'WZ', 'RWZ');
insert into carrier(name, iata, icao) values ('CONVIASA', 'V0', 'VCV');
insert into carrier(name, iata, icao) values ('CORSAIR', 'SS', 'CRL');
insert into carrier(name, iata, icao) values ('Calm Air International Ltd.', 'MO', 'CAV');
insert into carrier(name, iata, icao) values ('Canadian North Inc.', '5T', '');
insert into carrier(name, iata, icao) values ('Capital Cargo International', 'PT', '');
insert into carrier(name, iata, icao) values ('Capiteq Limited dba AIRNORTH', 'TL', 'ANO');
insert into carrier(name, iata, icao) values ('Cargo B Airlines', 'BB', 'CBB');
insert into carrier(name, iata, icao) values ('Cargoitalia S.p.A.', '2G', '');
insert into carrier(name, iata, icao) values ('Cargojet Airways Ltd.', 'W8', 'CJT');
insert into carrier(name, iata, icao) values ('Cargolux Airlines International S.A.', 'CV', 'CLX');
insert into carrier(name, iata, icao) values ('Carib Aviation Limited', '3Q', '');
insert into carrier(name, iata, icao) values ('Caribbean Airlines Limited', 'BW', 'BWA');
insert into carrier(name, iata, icao) values ('Caspian Airlines Service Company Ltd.', 'RV', 'CPN');
insert into carrier(name, iata, icao) values ('Catair Lineas Aereas S.A.(Clickair S.A.)', 'XG', '');
insert into carrier(name, iata, icao) values ('Cathay Pacific Airways Ltd.', 'CX', 'CPA');
insert into carrier(name, iata, icao) values ('Cayman Airways Limited', 'KX', 'CAY');
insert into carrier(name, iata, icao) values ('Central Mountain Air Ltd.', '9M', 'GLR');
insert into carrier(name, iata, icao) values ('Centurion Air Cargo, Inc.', 'WE', 'CWC');
insert into carrier(name, iata, icao) values ('Cetrafrrique Air Express (C.A.E.)', '6C', '');
insert into carrier(name, iata, icao) values ('Champlain Enterprises Inc.', 'C5', '');
insert into carrier(name, iata, icao) values ('Chautauqua Airlines Inc.', 'RP', 'CHQ');
insert into carrier(name, iata, icao) values ('China Airlines', 'CI', 'CAL');
insert into carrier(name, iata, icao) values ('China Cargo Airlines Ltd.', 'CK', '');
insert into carrier(name, iata, icao) values ('China Eastern Airlines', 'MU', 'CES');
insert into carrier(name, iata, icao) values ('China Postal Airlines Ltd.', '8Y', '');
insert into carrier(name, iata, icao) values ('China Southern Airlines', 'CZ', 'CSN');
insert into carrier(name, iata, icao) values ('China United Airlines', 'KN', 'CUA');
insert into carrier(name, iata, icao) values ('China West Air Co. Ltd.', 'PN', '');
insert into carrier(name, iata, icao) values ('Chongqing Airlines Co. Ltd', 'OQ', '');
insert into carrier(name, iata, icao) values ('Cielos del Peru, S.A.', 'A2', 'CIU');
insert into carrier(name, iata, icao) values ('Cielos del Sur S.A.', 'AU', 'AUT');
insert into carrier(name, iata, icao) values ('Cimber Air A.S.', 'QI', 'CIM');
insert into carrier(name, iata, icao) values ('City Airline AB', 'CF', 'SDR');
insert into carrier(name, iata, icao) values ('Cityjet', 'WX', 'BCY');
insert into carrier(name, iata, icao) values ('Cityline Hungary Kft', 'ZM', '');
insert into carrier(name, iata, icao) values ('Click Airways', 'C4', 'CGK');
insert into carrier(name, iata, icao) values ('Closed Joint Stock Company', 'C7', 'UZS');
insert into carrier(name, iata, icao) values ('Colgan Air', '9L', '');
insert into carrier(name, iata, icao) values ('Comair Ltd.', 'MN', 'CAW');
insert into carrier(name, iata, icao) values ('Comair, Inc.', 'OH', 'COM');
insert into carrier(name, iata, icao) values ('Compagnie Aerienne Corse', 'XK', 'CCM');
insert into carrier(name, iata, icao) values ('Compagnie Aerienne du Mali S.A.', 'I5', '');
insert into carrier(name, iata, icao) values ('Compania Boliviana de Transporte Aereo', '5L', '');
insert into carrier(name, iata, icao) values ('Compania Mexicana de Aviacion', 'MX', 'MXA');
insert into carrier(name, iata, icao) values ('Compania Panamena de Aviacion, S.A.', 'CM', 'CMP');
insert into carrier(name, iata, icao) values ('Compass Airlines Inc.', 'CP', '');
insert into carrier(name, iata, icao) values ('Concesionaria Vuela Compania De Aviacion', 'Y4', 'VOI');
insert into carrier(name, iata, icao) values ('Condor Flugdienst GmbH', 'DE', 'CFG');
insert into carrier(name, iata, icao) values ('Contact-Air Flugdienst GmbH & Co. KG', 'C3', 'KIS');
insert into carrier(name, iata, icao) values ('Continental Airlines, Inc.', 'CO', 'COA');
insert into carrier(name, iata, icao) values ('Continental Micronesia, Inc.', 'CS', 'CMI');
insert into carrier(name, iata, icao) values ('Corporate Air Charters, Inc.', '7V', '');
insert into carrier(name, iata, icao) values ('Cosmic Air Pvt. Ltd.', 'F5', '');
insert into carrier(name, iata, icao) values ('Coyne Airways Ltd', '7C', 'COY');
insert into carrier(name, iata, icao) values ('Croatia Airlines', 'OU', 'CTN');
insert into carrier(name, iata, icao) values ('Cubana de Aviacion S.A.', 'CU', 'CUB');
insert into carrier(name, iata, icao) values ('Custom Air Transport, Inc.', '5R', '');
insert into carrier(name, iata, icao) values ('Cyprus Airways Limited', 'CY', 'CYP');
insert into carrier(name, iata, icao) values ('Czech Airlines a.s., CSA', 'OK', 'CSA');
insert into carrier(name, iata, icao) values ('DHL Aero Expreso S.A.', 'D5', 'DAE');
insert into carrier(name, iata, icao) values ('DHL Air Limited', 'D0', 'DHK');
insert into carrier(name, iata, icao) values ('DHL International B.S.C. ( c )', 'ES', 'DHX');
insert into carrier(name, iata, icao) values ('DHL de Guatemala S.A.', 'L3', 'JOS');
insert into carrier(name, iata, icao) values ('Daallo Airlines', 'D3', 'DAO');
insert into carrier(name, iata, icao) values ('Daghestan Airlines', 'N2', '');
insert into carrier(name, iata, icao) values ('Dalavia - Far East Airways Khabarovsk', 'H8', 'KHB');
insert into carrier(name, iata, icao) values ('Dana Airlines Limited', '9J', 'DAN');
insert into carrier(name, iata, icao) values ('Danish Air Transport', 'DX', 'DTR');
insert into carrier(name, iata, icao) values ('Darwin Airline SA Lugano', '0D', 'DWT');
insert into carrier(name, iata, icao) values ('Deer Jet Co. Ltd.', 'JD', 'DER');
insert into carrier(name, iata, icao) values ('Delta Air Lines Inc.', 'DL', 'DAL');
insert into carrier(name, iata, icao) values ('Deutsche Lufthansa AG', 'LH', 'DLH');
insert into carrier(name, iata, icao) values ('Dnieproavia  - Joint Stock Aviation Co.', 'Z6', 'UDN');
insert into carrier(name, iata, icao) values ('Dolphin Air', 'ZD', '');
insert into carrier(name, iata, icao) values ('Domodedovo Airlines', 'E3', 'DMO');
insert into carrier(name, iata, icao) values ('Druk Air Corporation Ltd.', 'KB', 'DRK');
insert into carrier(name, iata, icao) values ('Dutch Antilles Express B.V.', '9H', '');
insert into carrier(name, iata, icao) values ('EVA Airways Corporation', 'BR', 'EVA');
insert into carrier(name, iata, icao) values ('East African Safari Air Express Ltd.', 'B5', '');
insert into carrier(name, iata, icao) values ('Edelweiss Air AG', 'WK', 'EDW');
insert into carrier(name, iata, icao) values ('Egyptair', 'MS', 'MSR');
insert into carrier(name, iata, icao) values ('El Al Israel Airlines Ltd.', 'LY', 'ELY');
insert into carrier(name, iata, icao) values ('El Sol de America', '6S', 'ESC');
insert into carrier(name, iata, icao) values ('Elysair S.A.S.', 'A0', '');
insert into carrier(name, iata, icao) values ('Emirates', 'EK', 'UAE');
insert into carrier(name, iata, icao) values ('Empire Airlines', 'EM', '');
insert into carrier(name, iata, icao) values ('Empire Aviation Limited', '', 'MPR');
insert into carrier(name, iata, icao) values ('Era Aviation, Inc.', '7H', 'ERH');
insert into carrier(name, iata, icao) values ('Eritrean Airlines', 'B8', 'ERT');
insert into carrier(name, iata, icao) values ('Estafeta Carga Aerea, S.A. de C.V', 'E7', '');
insert into carrier(name, iata, icao) values ('Estonian Air', 'OV', 'ELL');
insert into carrier(name, iata, icao) values ('Ethiopian Airlines Enterprise', 'ET', 'ETH');
insert into carrier(name, iata, icao) values ('Etihad Airways', 'EY', 'ETD');
insert into carrier(name, iata, icao) values ('Euro-Asia International JSC', '5B', '');
insert into carrier(name, iata, icao) values ('Eurocypria Airlines Ltd.', 'UI', 'ECA');
insert into carrier(name, iata, icao) values ('Eurofly S.p.A.', 'GJ', 'EEZ');
insert into carrier(name, iata, icao) values ('Euroline', '4L', 'MJX');
insert into carrier(name, iata, icao) values ('European Air Transport N.V.', 'QY', 'BCS');
insert into carrier(name, iata, icao) values ('Eurowings AG', 'EW', 'EWG');
insert into carrier(name, iata, icao) values ('Evergreen Helicopters International Inc.', '7E', '');
insert into carrier(name, iata, icao) values ('Evergreen International Airlines Inc.', 'EZ', 'EIA');
insert into carrier(name, iata, icao) values ('Execaire', 'MB', 'EXA');
insert into carrier(name, iata, icao) values ('Exploits Valley Air Services', '8K', '');
insert into carrier(name, iata, icao) values ('Expo Aviation (Pvt) Limited', '8D', 'EXV');
insert into carrier(name, iata, icao) values ('ExpressJet Airlines, Inc.', 'XE', 'BTA');
insert into carrier(name, iata, icao) values ('Eznis Airways Co. Ltd.', 'ZY', 'EZA');
insert into carrier(name, iata, icao) values ('Falcon Express Cargo Airlines', 'FC', '');
insert into carrier(name, iata, icao) values ('Fars Qeshm Airlines', 'QE', 'QFZ');
insert into carrier(name, iata, icao) values ('FedEx', 'FX', 'FDX');
insert into carrier(name, iata, icao) values ('Federal State Unitary Enterprise "STC', 'FV', 'PLK');
insert into carrier(name, iata, icao) values ('Felix Airways', 'FO', 'FXX');
insert into carrier(name, iata, icao) values ('Finnair Oyj', 'AY', 'FIN');
insert into carrier(name, iata, icao) values ('First Air', '7F', 'FAB');
insert into carrier(name, iata, icao) values ('Five Fourty Aviation Limited', '5H', 'FFV');
insert into carrier(name, iata, icao) values ('Florida West International Airways, Inc.', 'RF', 'FWL');
insert into carrier(name, iata, icao) values ('Fly Excellent', 'F3', 'FXL');
insert into carrier(name, iata, icao) values ('FlyFirefly Sdn. Bhd', 'FY', '');
insert into carrier(name, iata, icao) values ('FlyLAL-Lithuanian Airlines', 'TE', 'LIL');
insert into carrier(name, iata, icao) values ('Flybe Limited', 'BE', 'BEE');
insert into carrier(name, iata, icao) values ('Flying Carpet Air Transport & Services', '7Y', 'FCR');
insert into carrier(name, iata, icao) values ('Four Star Aviation', 'HK', 'FSC');
insert into carrier(name, iata, icao) values ('Friendship Airways', 'Y0', '');
insert into carrier(name, iata, icao) values ('Frontier Airlines, Inc.', 'F9', '');
insert into carrier(name, iata, icao) values ('Frontier Flying Service, Inc.', '2F', 'FTA');
insert into carrier(name, iata, icao) values ('Futura Gael', 'F6', 'FGL');
insert into carrier(name, iata, icao) values ('GB Airways Ltd.', 'GT', 'GBL');
insert into carrier(name, iata, icao) values ('GMG Airlines Ltd.', 'Z5', '');
insert into carrier(name, iata, icao) values ('Gabon Airlines', 'GY', '');
insert into carrier(name, iata, icao) values ('Gabon Airlines Cargo', '6G', 'GBK');
insert into carrier(name, iata, icao) values ('Gadair European Airlines', 'GP', 'GDR');
insert into carrier(name, iata, icao) values ('Gambia International Airlines Ltd.', 'GC', 'GNR');
insert into carrier(name, iata, icao) values ('Garuda Indonesia', 'GA', 'GIA');
insert into carrier(name, iata, icao) values ('Gazpromavia Aviation Company Ltd.', '4G', 'GZP');
insert into carrier(name, iata, icao) values ('Georgian Airways', 'A9', '');
insert into carrier(name, iata, icao) values ('Georgian National Airlines', 'QB', '');
insert into carrier(name, iata, icao) values ('Gestair S.A.', 'G5', '');
insert into carrier(name, iata, icao) values ('Ghana International Airlines Ltd.', 'G0', 'GHB');
insert into carrier(name, iata, icao) values ('Globespan Airways Limited', 'Y2', 'GSM');
insert into carrier(name, iata, icao) values ('Globus LLC', 'GH', '');
insert into carrier(name, iata, icao) values ('Go One Airways', 'GK', '');
insert into carrier(name, iata, icao) values ('GoJet Airlines LLC', 'G7', 'GJS');
insert into carrier(name, iata, icao) values ('Grand China Air Co. , Ltd.', 'CN', '');
insert into carrier(name, iata, icao) values ('Grand China Express Co. Ltd.', 'GS', '');
insert into carrier(name, iata, icao) values ('Grandstar Cargo International Airlines', 'GD', '');
insert into carrier(name, iata, icao) values ('Great Lakes Aviation Ltd.', 'ZK', 'GLA');
insert into carrier(name, iata, icao) values ('Great Wall Airlines Company Limited', 'IJ', '');
insert into carrier(name, iata, icao) values ('Gromov Flight Research Institute Airline', '3R', 'GAI');
insert into carrier(name, iata, icao) values ('Gulf & Caribbean Cargo, Inc', 'IF', '');
insert into carrier(name, iata, icao) values ('Gulf Air Company G.S.C.', 'GF', 'GFA');
insert into carrier(name, iata, icao) values ('Gulfstream International Airlines, Inc.', '3M', 'GFT');
insert into carrier(name, iata, icao) values ('HMY Airways Inc.', 'HQ', 'HMY');
insert into carrier(name, iata, icao) values ('Hahn Air Lines', 'HR', 'HHN');
insert into carrier(name, iata, icao) values ('Hainan Airlines Company Limited', 'HU', 'CHH');
insert into carrier(name, iata, icao) values ('Hamsal Air Services Limited', '2H', 'HML');
insert into carrier(name, iata, icao) values ('Hapag Lloyd Fluggesellschaft', 'HF', 'HLF');
insert into carrier(name, iata, icao) values ('Hawaii Island Air, Inc.', 'WP', '');
insert into carrier(name, iata, icao) values ('Hawaiian Airlines, Inc.', 'HA', 'HAL');
insert into carrier(name, iata, icao) values ('Heavylift Cargo Airlines Pty. Limited', 'HN', '');
insert into carrier(name, iata, icao) values ('Heli Air Monaco', 'YO', 'MCM');
insert into carrier(name, iata, icao) values ('Helijet International Inc.', 'JB', 'JBA');
insert into carrier(name, iata, icao) values ('Helitrans AS', '9I', 'HTA');
insert into carrier(name, iata, icao) values ('Hellenic Imperial Airways', 'HT', 'IMP');
insert into carrier(name, iata, icao) values ('Hello AG', 'HW', '');
insert into carrier(name, iata, icao) values ('Hemus Air', 'DU', '');
insert into carrier(name, iata, icao) values ('Hewa Bora Airways', 'EO', 'ALX');
insert into carrier(name, iata, icao) values ('Hi Fly Transportes Aereos, S.A.', '5K', '');
insert into carrier(name, iata, icao) values ('Highland Airways Limited', '8H', 'HWY');
insert into carrier(name, iata, icao) values ('Hokkaido Int''l Airlines Co., Ltd.', 'HD', 'ADO');
insert into carrier(name, iata, icao) values ('Homer Air Inc.', 'HB', '');
insert into carrier(name, iata, icao) values ('Hong Kong Airlines Limited', 'HX', '');
insert into carrier(name, iata, icao) values ('Hong Kong Dragon Airlines Limited', 'KA', 'HDA');
insert into carrier(name, iata, icao) values ('Hong Kong Express Airways Limited', 'UO', 'HKE');
insert into carrier(name, iata, icao) values ('Horizon Air', 'QX', 'QXE');
insert into carrier(name, iata, icao) values ('IBC Airways, Inc.', 'II', 'CSQ');
insert into carrier(name, iata, icao) values ('IHY Izmir Havayollari A.S.', '4I', 'IZM');
insert into carrier(name, iata, icao) values ('IMAIR Airline', 'IK', 'ITX');
insert into carrier(name, iata, icao) values ('Iberia - Lineas Aereas de Espana', 'IB', 'IBE');
insert into carrier(name, iata, icao) values ('Icaro S.A.', 'X8', '');
insert into carrier(name, iata, icao) values ('Icelandair', 'FI', 'ICE');
insert into carrier(name, iata, icao) values ('Indochina Airlines', 'IO', 'IDO');
insert into carrier(name, iata, icao) values ('Industrieflug IPS', 'I2', '');
insert into carrier(name, iata, icao) values ('Insel Air International B.V.', '7I', '');
insert into carrier(name, iata, icao) values ('Inter Express Hava Tasimacilik A.S.', '6K', 'INX');
insert into carrier(name, iata, icao) values ('Inter Globe Aviation Private Limited', '6E', '');
insert into carrier(name, iata, icao) values ('Inter-Aviation Services', 'D6', '');
insert into carrier(name, iata, icao) values ('InterSky Luftfahrt GmbH', '3L', 'ISK');
insert into carrier(name, iata, icao) values ('Interavia Airlines', 'ZA', '');
insert into carrier(name, iata, icao) values ('Interlink Airlines (Pty) Ltd.', 'ID', 'ITK');
insert into carrier(name, iata, icao) values ('International Air Cargo Company(LoadAir)', 'L8', '');
insert into carrier(name, iata, icao) values ('Interstate Airlines B.V.', 'I4', 'FWA');
insert into carrier(name, iata, icao) values ('Iran Air', 'IR', 'IRA');
insert into carrier(name, iata, icao) values ('Iran Aseman Airlines', 'EP', 'IRC');
insert into carrier(name, iata, icao) values ('Iraqi Airways', 'IA', 'IAW');
insert into carrier(name, iata, icao) values ('Island Aviation Services Ltd.', 'Q2', '');
insert into carrier(name, iata, icao) values ('Islena de Inversiones S.A. de C.V.', 'WC', 'ISV');
insert into carrier(name, iata, icao) values ('Israir Airlines and Tourism Ltd.', '6H', 'ISR');
insert into carrier(name, iata, icao) values ('Ivoirienne De Transport Aerien', 'I3', '');
insert into carrier(name, iata, icao) values ('JAL Express', 'JC', '');
insert into carrier(name, iata, icao) values ('JALways Co. Ltd.', 'JO', 'JAZ');
insert into carrier(name, iata, icao) values ('JET AIR Spolka z o.o.', 'O2', '');
insert into carrier(name, iata, icao) values ('JSC "Aircompany SCAT"', 'DV', '');
insert into carrier(name, iata, icao) values ('JSC "KAPO Avia"', 'G7', 'KAO');
insert into carrier(name, iata, icao) values ('JSC "Starline.kz"', 'DZ', 'LMZ');
insert into carrier(name, iata, icao) values ('Jade Cargo International Company Limited', 'JI', 'JAE');
insert into carrier(name, iata, icao) values ('Japan Airlines International Co., Ltd.', 'JL', 'JAL');
insert into carrier(name, iata, icao) values ('Japan Transocean Air Co. Ltd.', 'NU', 'JTA');
insert into carrier(name, iata, icao) values ('Jat  Airways', 'JU', 'JAT');
insert into carrier(name, iata, icao) values ('Jet 4 You', '8J', '');
insert into carrier(name, iata, icao) values ('Jet Airways (India) Limited', '9W', 'JAI');
insert into carrier(name, iata, icao) values ('Jet Airways Inc.', 'QJ', '');
insert into carrier(name, iata, icao) values ('Jet Aviation Business Jets AG', 'PP', 'PJS');
insert into carrier(name, iata, icao) values ('Jet Link Express Ltd.', 'J0', '');
insert into carrier(name, iata, icao) values ('Jet Lite (India) Limited', 'S2', '');
insert into carrier(name, iata, icao) values ('Jet2.com Limited', 'LS', 'EXS');
insert into carrier(name, iata, icao) values ('JetClub AG', '0J', 'JCS');
insert into carrier(name, iata, icao) values ('JetX ehf, (Primera Air)', 'GX', 'JXX');
insert into carrier(name, iata, icao) values ('Jetstar Asia Airways Pte Ltd', '3K', 'JSA');
insert into carrier(name, iata, icao) values ('Jetstar Pacific Airlines', 'BL', 'PIC');
insert into carrier(name, iata, icao) values ('Jett8 Airlines Cargo Pte Ltd.', 'JX', '');
insert into carrier(name, iata, icao) values ('Job Air s.r.o.', '3B', 'JBR');
insert into carrier(name, iata, icao) values ('Joint Stock Company " Air Company', 'DW', 'UCR');
insert into carrier(name, iata, icao) values ('Joint Stock Company "Omskavia" Airlines', 'N3', 'OMS');
insert into carrier(name, iata, icao) values ('Joint Stock Company Aircompany "Yakutia"', 'R3', 'SVL');
insert into carrier(name, iata, icao) values ('Joint Stock Company SIAT (Sibaviatrans)', '5M', '');
insert into carrier(name, iata, icao) values ('Joint- Stock Company "Sakhalinskie', 'HZ', 'SHU');
insert into carrier(name, iata, icao) values ('Jordan Aviation', 'R5', 'JAV');
insert into carrier(name, iata, icao) values ('Jordan International Air Cargo', 'J4', '');
insert into carrier(name, iata, icao) values ('Jubba Airways', '6J', 'JUB');
insert into carrier(name, iata, icao) values ('Juneyao Airlines Co,. Ltd.', 'HO', 'DKH');
insert into carrier(name, iata, icao) values ('K-Mile Air Co. Ltd', '8K', 'KMI');
insert into carrier(name, iata, icao) values ('KD Avia Open Joint Stock Company', 'KD', 'KNI');
insert into carrier(name, iata, icao) values ('KLM Cityhopper', 'WA', 'KLC');
insert into carrier(name, iata, icao) values ('KLM Royal Dutch Airlines', 'KL', 'KLM');
insert into carrier(name, iata, icao) values ('Kalitta Air, LLC', 'K4', '');
insert into carrier(name, iata, icao) values ('Kalitta Charters II, LLC', 'CB', 'KFS');
insert into carrier(name, iata, icao) values ('Kam Air', 'RQ', 'KMF');
insert into carrier(name, iata, icao) values ('Kampuchea Airlines', 'E2', 'KMP');
insert into carrier(name, iata, icao) values ('Kenosha Aero, Inc. dba Alliance Airlines', '3A', 'AFJ');
insert into carrier(name, iata, icao) values ('Kenya Airways', 'KQ', 'KQA');
insert into carrier(name, iata, icao) values ('Key Lime Air Corporation', 'KG', 'LYM');
insert into carrier(name, iata, icao) values ('Kibris Turk Hava Yollari', 'YK', 'KYV');
insert into carrier(name, iata, icao) values ('Kingfisher Airlines Limited', 'IT', '');
insert into carrier(name, iata, icao) values ('Kish Airlines', 'Y9', 'IRK');
insert into carrier(name, iata, icao) values ('Kitty Hawk Aircargo, Inc.', 'KR', 'KHA');
insert into carrier(name, iata, icao) values ('Korean Air Lines Co. Ltd.', 'KE', 'KAL');
insert into carrier(name, iata, icao) values ('Kunming Airlines', 'KY', '');
insert into carrier(name, iata, icao) values ('Kunpeng Airlines Co., Ltd', 'VD', '');
insert into carrier(name, iata, icao) values ('Kuwait Airways', 'KU', 'KAC');
insert into carrier(name, iata, icao) values ('Kuzu Airlines Cargo', 'GO', 'KZU');
insert into carrier(name, iata, icao) values ('L.A.B. Flying Service Inc.', 'JF', 'LAB');
insert into carrier(name, iata, icao) values ('LAM - Linhas Aereas de Mocambique', 'TM', 'LAM');
insert into carrier(name, iata, icao) values ('LIAT (1974) Ltd.', 'LI', 'LIA');
insert into carrier(name, iata, icao) values ('LOT - Polish Airlines', 'LO', 'LOT');
insert into carrier(name, iata, icao) values ('LTE International Airways S.A.', 'XO', 'LTE');
insert into carrier(name, iata, icao) values ('LTU International Airways', 'LT', 'LTU');
insert into carrier(name, iata, icao) values ('Labrador Airways Limited', 'WJ', 'LAL');
insert into carrier(name, iata, icao) values ('Lagun Air', 'N7', '');
insert into carrier(name, iata, icao) values ('Lan Airlines S.A.', 'LA', 'LAN');
insert into carrier(name, iata, icao) values ('Lan Chile Cargo S.A.', 'UC', 'LCO');
insert into carrier(name, iata, icao) values ('Lan Ecuador - Aerolane Lineas Aereas', 'XL', '');
insert into carrier(name, iata, icao) values ('Lan Peru S.A.', 'LP', 'LPE');
insert into carrier(name, iata, icao) values ('LankAir Private Limited', 'IL', '');
insert into carrier(name, iata, icao) values ('Lao Airlines', 'QV', 'LAO');
insert into carrier(name, iata, icao) values ('Laparkan Airways, Inc.', 'LE', '');
insert into carrier(name, iata, icao) values ('Lauda Air Luftfahrt AG', 'NG', 'LDA');
insert into carrier(name, iata, icao) values ('Libyan Airlines', 'LN', 'LAA');
insert into carrier(name, iata, icao) values ('Lignes Aeriennes Congolaises', '4V', '');
insert into carrier(name, iata, icao) values ('Limited Liability Company', '7D', 'UDC');
insert into carrier(name, iata, icao) values ('Linea Aerea Carguera de Colombia S.A.', 'L7', '');
insert into carrier(name, iata, icao) values ('Linea Aerea de Servicio Ejecutivo', 'QL', 'LER');
insert into carrier(name, iata, icao) values ('Lineas Aereas Costarricenses S.A.', 'LR', 'LRC');
insert into carrier(name, iata, icao) values ('Linkair Express S.p.A', '6M', '');
insert into carrier(name, iata, icao) values ('Livingston S.p.A.', 'LM', 'LVG');
insert into carrier(name, iata, icao) values ('Lucky Air Co. Ltd.', '8L', '');
insert into carrier(name, iata, icao) values ('Lufthansa Cargo AG', 'LH', 'GEC');
insert into carrier(name, iata, icao) values ('Lufthansa CityLine GmbH', 'CL', 'CLH');
insert into carrier(name, iata, icao) values ('Lufttransport AS', 'L5', '');
insert into carrier(name, iata, icao) values ('Luxair', 'LG', 'LGL');
insert into carrier(name, iata, icao) values ('Lviv Airlines', '5V', 'UKW');
insert into carrier(name, iata, icao) values ('Lynden Air Cargo, LLC', 'L2', '');
insert into carrier(name, iata, icao) values ('MDLR Airlines Pvt. Ltd.', '9Y', '');
insert into carrier(name, iata, icao) values ('MIAT - Mongolian Airlines', 'OM', 'MGL');
insert into carrier(name, iata, icao) values ('MK Airlines Limited', '7G', 'MKA');
insert into carrier(name, iata, icao) values ('MN Airlines LLC', 'SY', 'SCX');
insert into carrier(name, iata, icao) values ('MNG Airlines Cargo', 'MB', 'MNB');
insert into carrier(name, iata, icao) values ('MR Lines', 'XV', '');
insert into carrier(name, iata, icao) values ('MYAIR.com', '8I', '');
insert into carrier(name, iata, icao) values ('Macair Jet S.A.', 'VM', '');
insert into carrier(name, iata, icao) values ('Macedonian Airlnes', 'IN', 'MAK');
insert into carrier(name, iata, icao) values ('Mahan Airlines', 'W5', 'IRM');
insert into carrier(name, iata, icao) values ('Malaysia  Airline System Berhad', 'MH', 'MAS');
insert into carrier(name, iata, icao) values ('Malev Hungarian Airlines  Limited', 'MA', 'MAH');
insert into carrier(name, iata, icao) values ('Mandarin Airlines Ltd.', 'AE', 'MDA');
insert into carrier(name, iata, icao) values ('Martinair Holland N.V.', 'MP', 'MPH');
insert into carrier(name, iata, icao) values ('Mauritania Airways', 'YD', 'MTW');
insert into carrier(name, iata, icao) values ('Maximus Air Cargo', '', 'MXU');
insert into carrier(name, iata, icao) values ('Med View Airlines (NIG) Ltd.', 'VL', '');
insert into carrier(name, iata, icao) values ('Mediterranean Aviation Company Ltd.', 'N5', 'MDM');
insert into carrier(name, iata, icao) values ('Mercury Air Cargo, Inc.', '4X', '');
insert into carrier(name, iata, icao) values ('Meridiana African Airlines (U) Limited', 'U7', '');
insert into carrier(name, iata, icao) values ('Meridiana S.p.A.', 'IG', 'ISS');
insert into carrier(name, iata, icao) values ('Merpati Nusantara Airlines', 'MZ', 'MNA');
insert into carrier(name, iata, icao) values ('Mesa Airlines, Inc.', 'YV', 'ASH');
insert into carrier(name, iata, icao) values ('Mesaba Aviation Inc.', 'XJ', 'MES');
insert into carrier(name, iata, icao) values ('Mid Asia Airlines Limited', 'BH', '');
insert into carrier(name, iata, icao) values ('Middle East Airlines AirLiban', 'ME', 'MEA');
insert into carrier(name, iata, icao) values ('Midex Airlines', 'MG', '');
insert into carrier(name, iata, icao) values ('Midwest Airlines Inc.', 'YX', 'MEP');
insert into carrier(name, iata, icao) values ('Mihin Lanka (Pvt) Ltd.', 'MJ', 'MLR');
insert into carrier(name, iata, icao) values ('Mistral Air S.r.l.', '7M', 'MSA');
insert into carrier(name, iata, icao) values ('Mokulele Flight Service', 'MW', '');
insert into carrier(name, iata, icao) values ('Moldavian Airlines', '2M', 'MDV');
insert into carrier(name, iata, icao) values ('Monarch Airlines', 'ZB', 'MON');
insert into carrier(name, iata, icao) values ('Montenegro Airlines', 'YM', 'MGX');
insert into carrier(name, iata, icao) values ('Motor-Sich JSC', 'M9', '');
insert into carrier(name, iata, icao) values ('Mountain Air Cargo Inc.', 'C2', 'MTN');
insert into carrier(name, iata, icao) values ('Murray Air Inc.', 'N8', 'MUA');
insert into carrier(name, iata, icao) values ('MyTravel Airways Limited', 'VZ', 'MYT');
insert into carrier(name, iata, icao) values ('Myanma Airways', 'UB', 'UBA');
insert into carrier(name, iata, icao) values ('Myanmar Airways International', '8M', '');
insert into carrier(name, iata, icao) values ('NACIL, dba Air India', 'AI', 'AIC');
insert into carrier(name, iata, icao) values ('NACIL, dba Indian Airlines', 'IC', 'IAC');
insert into carrier(name, iata, icao) values ('NOVA Airlines', 'O9', 'NOV');
insert into carrier(name, iata, icao) values ('Nasair', 'UE', '');
insert into carrier(name, iata, icao) values ('National Airways Cameroon', '9O', '');
insert into carrier(name, iata, icao) values ('Nauru Air Corporation', 'ON', 'RON');
insert into carrier(name, iata, icao) values ('Naysa', 'ZN', 'NAY');
insert into carrier(name, iata, icao) values ('Nayzak Air Transport Company', 'M4', 'NZA');
insert into carrier(name, iata, icao) values ('Neos S.P.A.', 'NO', '');
insert into carrier(name, iata, icao) values ('New Axis Airways', '9X', 'AXY');
insert into carrier(name, iata, icao) values ('Nippon Cargo Airlines', 'KZ', 'NCA');
insert into carrier(name, iata, icao) values ('Nordic Airlink Holding AB dba flynordic', 'LF', 'NDC');
insert into carrier(name, iata, icao) values ('North American Airlines, Inc.', 'NA', 'NAO');
insert into carrier(name, iata, icao) values ('Northeastern Airlines Co. Ltd.', 'NS', '');
insert into carrier(name, iata, icao) values ('Northern Air Cargo, Inc.', 'NC', '');
insert into carrier(name, iata, icao) values ('Northwest Airlines, Inc.', 'NW', 'NWA');
insert into carrier(name, iata, icao) values ('Northwestern Air Lease Ltd.', 'J3', 'PLR');
insert into carrier(name, iata, icao) values ('Norwegian Air Shuttle A.S.', 'DY', 'NAX');
insert into carrier(name, iata, icao) values ('Nova Airlines AB', 'N9', 'NVR');
insert into carrier(name, iata, icao) values ('OLT-Ostfriesische Lufttransport GmbH', 'OL', 'OLT');
insert into carrier(name, iata, icao) values ('OOO "Atran "', 'V8', 'VAS');
insert into carrier(name, iata, icao) values ('Oceanair Linhas Aereas Ltda.', 'O6', 'ONE');
insert into carrier(name, iata, icao) values ('Okay Airways Company Limited', 'BK', '');
insert into carrier(name, iata, icao) values ('Olympic Airlines', 'OA', 'OAL');
insert into carrier(name, iata, icao) values ('Oman Air (SAOG)', 'WY', 'OAS');
insert into carrier(name, iata, icao) values ('One Two Go Airlines Co. Ltd.', 'OG', 'OTG');
insert into carrier(name, iata, icao) values ('Onur Havayollari Tasimacilik A.S.', '8Q', 'OHY');
insert into carrier(name, iata, icao) values ('Operador Aereo Andalus S.A.', 'EA', 'ANU');
insert into carrier(name, iata, icao) values ('Orenburg Airlines Federal State', 'R2', 'ORB');
insert into carrier(name, iata, icao) values ('Orient Thai Airlines', 'OX', '');
insert into carrier(name, iata, icao) values ('Overland Airways Limited', 'OJ', 'OLA');
insert into carrier(name, iata, icao) values ('OzJet Airlines Pty Ltd', 'O7', '');
insert into carrier(name, iata, icao) values ('PB Air Company Limited', '9Q', 'PBA');
insert into carrier(name, iata, icao) values ('PT Cardig Air', '8F', 'CRG');
insert into carrier(name, iata, icao) values ('PT Republic Express Airlines', 'RH', '');
insert into carrier(name, iata, icao) values ('PT. Indonesia Air Transport. Tbk', 'I8', 'IDA');
insert into carrier(name, iata, icao) values ('PT. Indonesia AirAsia', 'QZ', 'AWQ');
insert into carrier(name, iata, icao) values ('PT. Megantara Air', '9M', 'MKE');
insert into carrier(name, iata, icao) values ('PT. Sriwijaya Air', 'SJ', '');
insert into carrier(name, iata, icao) values ('Pacific Airways Inc.', '3F', '');
insert into carrier(name, iata, icao) values ('Pacific East Asia Cargo Airlines, Inc.', 'Q8', 'PEC');
insert into carrier(name, iata, icao) values ('Pacific Wings, L.L.C.', 'LW', 'ANV');
insert into carrier(name, iata, icao) values ('Pak West Airlines Inc.', 'P8', 'PKW');
insert into carrier(name, iata, icao) values ('Pakistan International Airlines', 'PK', 'PIA');
insert into carrier(name, iata, icao) values ('Palau Asia Pacific Air Inc.', '0P', '');
insert into carrier(name, iata, icao) values ('Palau National Airlines', '9P', '');
insert into carrier(name, iata, icao) values ('Pan Am World Airways Dominicana', '7Q', 'PWD');
insert into carrier(name, iata, icao) values ('Paramount Airways Pvt. Ltd.', 'I7', '');
insert into carrier(name, iata, icao) values ('Pascan Aviation Inc.', 'P6', 'PSC');
insert into carrier(name, iata, icao) values ('Pegasus Hava Tasimaciligi A.S.', 'H9', '');
insert into carrier(name, iata, icao) values ('Penair', 'KS', 'PEN');
insert into carrier(name, iata, icao) values ('Philippine Airlines, Inc.', 'PR', 'PAL');
insert into carrier(name, iata, icao) values ('Piedmont Airlines, Inc.', 'US', '');
insert into carrier(name, iata, icao) values ('Pinnacle Airlines Inc.', '9E', 'FLG');
insert into carrier(name, iata, icao) values ('Platnium Air Linhas Aereas Ltda.', 'P2', 'PLS');
insert into carrier(name, iata, icao) values ('Polar Air Cargo Worldwide, Inc.', 'PO', '');
insert into carrier(name, iata, icao) values ('Polar Airlines de Mexico S.A. de C.V.', 'M4', 'PMO');
insert into carrier(name, iata, icao) values ('Porter Airlines Inc.', 'PD', '');
insert into carrier(name, iata, icao) values ('Portugalia - Companhia Portuguesa de', 'NI', 'PGA');
insert into carrier(name, iata, icao) values ('Premier Trans Aire Inc.', '3X', '');
insert into carrier(name, iata, icao) values ('Prescott Support Company', 'PM', 'PSK');
insert into carrier(name, iata, icao) values ('Primaris Airlines, Inc.', 'FE', '');
insert into carrier(name, iata, icao) values ('Primeras Lineas Uruguayas de Navegacion', 'PU', 'PUA');
insert into carrier(name, iata, icao) values ('Progress Multitrade Co., Ltd.', 'U4', '');
insert into carrier(name, iata, icao) values ('Propilot, Inc.', 'F3', '');
insert into carrier(name, iata, icao) values ('Provincial Airlines', 'PB', 'SPR');
insert into carrier(name, iata, icao) values ('Puerto Rico Air Management Service Inc.', '2P', '');
insert into carrier(name, iata, icao) values ('Pullmantur Air', 'EB', '');
insert into carrier(name, iata, icao) values ('Qantas Airways Ltd.', 'QF', 'QFA');
insert into carrier(name, iata, icao) values ('Qatar Airways(Q.C.S.C)', 'QR', 'QTR');
insert into carrier(name, iata, icao) values ('RACSA Airlines', 'R6', '');
insert into carrier(name, iata, icao) values ('RAK Airways', 'RT', '');
insert into carrier(name, iata, icao) values ('REGIONAL EXPRESS PTY LIMITED', 'ZL', '');
insert into carrier(name, iata, icao) values ('Redemption Inc.', '2O', '');
insert into carrier(name, iata, icao) values ('Regional Air Lines', 'FN', 'RGL');
insert into carrier(name, iata, icao) values ('Regional Compagnie Aerienne Europeenne', 'YS', '');
insert into carrier(name, iata, icao) values ('Romanian Aviation Company', 'WQ', 'RMV');
insert into carrier(name, iata, icao) values ('Royal Air Maroc', 'AT', 'RAM');
insert into carrier(name, iata, icao) values ('Royal Airways Limited', 'SG', 'MOD');
insert into carrier(name, iata, icao) values ('Royal Brunei Airlines Sdn. Bhd.', 'BI', 'RBA');
insert into carrier(name, iata, icao) values ('Royal Daisy Airlines', '6D', 'KDR');
insert into carrier(name, iata, icao) values ('Royal Falcon', 'RZ', 'RFJ');
insert into carrier(name, iata, icao) values ('Royal Jordanian', 'RJ', 'RJA');
insert into carrier(name, iata, icao) values ('Royal Nepal Airlines Corporation', 'RA', 'RNA');
insert into carrier(name, iata, icao) values ('Rutas Aereas, C.A. RUTACA', 'RM', 'RUC');
insert into carrier(name, iata, icao) values ('Rwandair Express', 'WB', 'RWD');
insert into carrier(name, iata, icao) values ('Ryan International Airlines', 'RD', 'RYN');
insert into carrier(name, iata, icao) values ('Ryanair Ltd.', 'FR', 'RYR');
insert into carrier(name, iata, icao) values ('SA  Airlink', '4Z', '');
insert into carrier(name, iata, icao) values ('SAS Scandinavian Airlines Norge AS', 'BU', 'CNO');
insert into carrier(name, iata, icao) values ('SATA - Air Acores', 'SP', 'SAT');
insert into carrier(name, iata, icao) values ('SATA International Servicos e', 'S4', 'RZO');
insert into carrier(name, iata, icao) values ('SEVENAIR S.A.', 'UG', 'TUI');
insert into carrier(name, iata, icao) values ('SOL S.A. Lineas Aereas', '8R', '');
insert into carrier(name, iata, icao) values ('SWIFT AIR,L.L.C.', 'Q7', 'SWQ');
insert into carrier(name, iata, icao) values ('SWISS International Air Lines Ltd', 'LX', 'SWR');
insert into carrier(name, iata, icao) values ('Safair (Proprietary) Ltd.', 'FA', 'SFR');
insert into carrier(name, iata, icao) values ('Safi Airways Ltd.', '4Q', 'SFW');
insert into carrier(name, iata, icao) values ('Sama Air LLC', 'S8', '');
insert into carrier(name, iata, icao) values ('Sama Airways Ltd.', 'ZS', '');
insert into carrier(name, iata, icao) values ('Samara Airlines', 'E5', 'BRZ');
insert into carrier(name, iata, icao) values ('Saudi Arabian Airlines', 'SV', 'SVA');
insert into carrier(name, iata, icao) values ('Sayakhat Airlines', 'W7', 'SAH');
insert into carrier(name, iata, icao) values ('Scandinavian Airlines System (SAS)', 'SK', 'SAS');
insert into carrier(name, iata, icao) values ('Scenic Airlines, Inc.', 'YR', 'EGJ');
insert into carrier(name, iata, icao) values ('Servicios Aereos Nacionales S.A.', 'RZ', 'LRS');
insert into carrier(name, iata, icao) values ('Shaheen Air International', 'NL', 'SAI');
insert into carrier(name, iata, icao) values ('Sham Wings Airlines', '6Q', 'SAW');
insert into carrier(name, iata, icao) values ('Shandong Airlines', 'SC', 'CDG');
insert into carrier(name, iata, icao) values ('Shanghai Airlines Cargo International', 'F4', 'SHQ');
insert into carrier(name, iata, icao) values ('Shanghai Airlines Co. Ltd.', 'FM', '');
insert into carrier(name, iata, icao) values ('Shenzhen Airlines', 'ZH', 'CSZ');
insert into carrier(name, iata, icao) values ('Shenzhen Donghai Airlines Co., Ltd', 'J5', '');
insert into carrier(name, iata, icao) values ('Shun Tak-China Travel Ship Mgmt. Ltd.', '8S', '');
insert into carrier(name, iata, icao) values ('Shuttle America', 'S5', '');
insert into carrier(name, iata, icao) values ('Siberia Airlines', 'S7', 'SBI');
insert into carrier(name, iata, icao) values ('Sichuan Airlines Co. Ltd.', '3U', '');
insert into carrier(name, iata, icao) values ('Siem Reap Airways International', 'FT', 'SRH');
insert into carrier(name, iata, icao) values ('Silk Way Airlines', 'ZP', '');
insert into carrier(name, iata, icao) values ('SilkAir (S) Pte. Ltd.', 'MI', 'SLK');
insert into carrier(name, iata, icao) values ('Singapore Airlines Cargo Pte. Ltd.', 'SQ', 'SQC');
insert into carrier(name, iata, icao) values ('Singapore Airlines Limited', 'SQ', 'SIA');
insert into carrier(name, iata, icao) values ('Sky Air World Pty Ltd', 'S9', '');
insert into carrier(name, iata, icao) values ('Sky Express', 'XW', '');
insert into carrier(name, iata, icao) values ('Sky Express S.A.', 'GQ', 'SHE');
insert into carrier(name, iata, icao) values ('Sky Gabon S.A.', 'GV', 'SKG');
insert into carrier(name, iata, icao) values ('Sky Jet Aviation Ltd', 'UQ', 'SJA');
insert into carrier(name, iata, icao) values ('Sky Service S.A. dba Sky Airline', 'H2', 'SKU');
insert into carrier(name, iata, icao) values ('Sky Way Enterprises Inc.', 'KI', 'SKZ');
insert into carrier(name, iata, icao) values ('SkyStar Airways Company Limited', 'XT', 'SKT');
insert into carrier(name, iata, icao) values ('SkyWest  Airlines', 'OO', 'SKW');
insert into carrier(name, iata, icao) values ('Skybus Airlines, LLC', 'SX', '');
insert into carrier(name, iata, icao) values ('Skymark Airlines Inc.', 'BC', 'SKY');
insert into carrier(name, iata, icao) values ('Skynet Asia Airways Co., Ltd.', 'LQ', '');
insert into carrier(name, iata, icao) values ('Skyservice Airlines Inc.', '5G', 'SSV');
insert into carrier(name, iata, icao) values ('Skyways AB', 'JZ', 'SKX');
insert into carrier(name, iata, icao) values ('Skywest Airlines Pty. Ltd.', 'XR', '');
insert into carrier(name, iata, icao) values ('Sociedad Aeronautica de Medellin', 'MM', 'SAM');
insert into carrier(name, iata, icao) values ('Societe De Transport De L''Archipel', 'OG', '');
insert into carrier(name, iata, icao) values ('Societe Nouvelle Air Ivoire', 'VU', '');
insert into carrier(name, iata, icao) values ('Solar Cargo, C.A.', '4S', 'OLC');
insert into carrier(name, iata, icao) values ('Solomon Airlines', 'IE', 'SOL');
insert into carrier(name, iata, icao) values ('South African Airways', 'SA', 'SAA');
insert into carrier(name, iata, icao) values ('South-East European Airlines', 'G2', 'GGG');
insert into carrier(name, iata, icao) values ('Southern Air Inc.', '9S', 'SOO');
insert into carrier(name, iata, icao) values ('Southwest Airlines Co.', 'WN', 'SWA');
insert into carrier(name, iata, icao) values ('Spanair S.A.', 'JK', 'JKK');
insert into carrier(name, iata, icao) values ('Spirit Airlines', 'NK', '');
insert into carrier(name, iata, icao) values ('Spring Airlines Limited Corporation', '9C', '');
insert into carrier(name, iata, icao) values ('SriLankan Airlines Limited', 'UL', 'ALK');
insert into carrier(name, iata, icao) values ('Stabo Air Limited', '', 'SBO');
insert into carrier(name, iata, icao) values ('Star Air A/S', 'S6', 'SRR');
insert into carrier(name, iata, icao) values ('Star Equatorial Airlines', '2S', '');
insert into carrier(name, iata, icao) values ('Star Up S.A.', '2I', 'SRU');
insert into carrier(name, iata, icao) values ('Starlight Airline', 'QP', 'SLT');
insert into carrier(name, iata, icao) values ('Sterling Airlines A/S', 'NB', '');
insert into carrier(name, iata, icao) values ('Sudan Airways Co. Ltd.', 'SD', 'SUD');
insert into carrier(name, iata, icao) values ('SunExpress', 'XQ', 'SXS');
insert into carrier(name, iata, icao) values ('Sunwing Airlines Inc.', 'WG', '');
insert into carrier(name, iata, icao) values ('Surinam Airways Ltd.', 'PY', 'SLM');
insert into carrier(name, iata, icao) values ('Swiftair', '7J', 'SWT');
insert into carrier(name, iata, icao) values ('Syrian Arab Airlines', 'RB', 'SYR');
insert into carrier(name, iata, icao) values ('TAAG - Linhas Aereas de Angola', 'DT', 'DTA');
insert into carrier(name, iata, icao) values ('TACA Costa Rica Sociedad Anonima', 'TI', 'TAT');
insert into carrier(name, iata, icao) values ('TAM - Transportes Aereos del', 'PZ', 'LAP');
insert into carrier(name, iata, icao) values ('TAM Linhas Aereas S.A.', 'JJ', 'TAM');
insert into carrier(name, iata, icao) values ('TAME Linea Aerea del Ecuador', 'EQ', 'TAE');
insert into carrier(name, iata, icao) values ('TAP - Air Portugal', 'TP', 'TAP');
insert into carrier(name, iata, icao) values ('TAROM - Transporturile Aeriene Romane', 'RO', 'ROT');
insert into carrier(name, iata, icao) values ('TNT Airways S.A.', '3V', 'TAY');
insert into carrier(name, iata, icao) values ('TRIP Transporte Aereos Regionais Do', 'T4', '');
insert into carrier(name, iata, icao) values ('TUI Airlines Nederland B.V.', 'OR', 'TFL');
insert into carrier(name, iata, icao) values ('TUIfly Nordic AB', '6B', 'BLX');
insert into carrier(name, iata, icao) values ('Taca International Airlines, S.A.', 'TA', 'TAI');
insert into carrier(name, iata, icao) values ('Taf Linhas Aereas S.A.', 'R9', 'TSD');
insert into carrier(name, iata, icao) values ('Tandem Aero Ltd.', 'TQ', 'TDM');
insert into carrier(name, iata, icao) values ('Tasman Cargo Airlines PTY LTD', 'HJ', '');
insert into carrier(name, iata, icao) values ('Tatarstan JSC Aircompany', 'U9', '');
insert into carrier(name, iata, icao) values ('Tatonduk Outfitters Limited.', '3Z', '');
insert into carrier(name, iata, icao) values ('Taxi Fly Group S.A.', 'P5', 'JPR');
insert into carrier(name, iata, icao) values ('Tbilaviamsheni', 'L6', 'VNZ');
insert into carrier(name, iata, icao) values ('Thai AirAsia Co., Ltd.', 'FD', '');
insert into carrier(name, iata, icao) values ('Thai Airways International Public', 'TG', 'THA');
insert into carrier(name, iata, icao) values ('Thomas Cook Airlines Scandinavia A/S', 'DK', 'VKG');
insert into carrier(name, iata, icao) values ('Thomas Cook Airlines U.K. Limited', 'MT', 'TCX');
insert into carrier(name, iata, icao) values ('Thomson Airways Limited', 'BY', 'TOM');
insert into carrier(name, iata, icao) values ('Tiara Air N.V.', '3P', '');
insert into carrier(name, iata, icao) values ('Titan Airways Limited', 'ZT', 'AWC');
insert into carrier(name, iata, icao) values ('Toumai Air Tchad', '9D', '');
insert into carrier(name, iata, icao) values ('Trade Air Ltd.', '8P', 'TDR');
insert into carrier(name, iata, icao) values ('Tradewinds Airlines Inc.', 'WI', '');
insert into carrier(name, iata, icao) values ('Trans Air Benin', 'N4', 'TNB');
insert into carrier(name, iata, icao) values ('Trans American Airlines, S.A. TACA PERU', 'T0', '');
insert into carrier(name, iata, icao) values ('Trans States Airlines, Inc.', 'AX', 'LOF');
insert into carrier(name, iata, icao) values ('TransAsia Airways Corporation', 'GE', 'TNA');
insert into carrier(name, iata, icao) values ('Transaero Airlines', 'UN', 'TSO');
insert into carrier(name, iata, icao) values ('Transavia Airlines', 'HV', 'TRA');
insert into carrier(name, iata, icao) values ('Transaviaexport Cargo Airline', 'AL', 'TXC');
insert into carrier(name, iata, icao) values ('Transcarga Int''l Airways, C.A.', 'T9', '');
insert into carrier(name, iata, icao) values ('Transmile Air Services Sdn. Bhd.', 'TH', '');
insert into carrier(name, iata, icao) values ('Transport Africa', '9K', 'TFZ');
insert into carrier(name, iata, icao) values ('Transporte Aereo S.A.', 'LU', '');
insert into carrier(name, iata, icao) values ('Transportes Aereos Bolivianos', '', 'BOL');
insert into carrier(name, iata, icao) values ('Transportes Aereos Cielos Andinos S.A.C.', '9P', 'CIE');
insert into carrier(name, iata, icao) values ('Transportes Aereos Mercantiles', 'QT', 'TPA');
insert into carrier(name, iata, icao) values ('Transportes Aereos de Cabo Verde', 'VR', 'TCV');
insert into carrier(name, iata, icao) values ('Transportes Aeromar, S.A. de C.V.', 'VW', 'TAO');
insert into carrier(name, iata, icao) values ('Trast Aero', 'S5', 'TSJ');
insert into carrier(name, iata, icao) values ('Tunca Havacilik A.S. BestAir', '5F', '');
insert into carrier(name, iata, icao) values ('Tunisair', 'TU', 'TAR');
insert into carrier(name, iata, icao) values ('Turan Air Airline Company', '3T', 'URN');
insert into carrier(name, iata, icao) values ('Turkish Airlines Inc.', 'TK', 'THY');
insert into carrier(name, iata, icao) values ('Turkmenistan Airlines', 'T5', 'TUA');
insert into carrier(name, iata, icao) values ('Turks Air', '6T', '');
insert into carrier(name, iata, icao) values ('Turkuaz Airlines', 'HK', 'TRK');
insert into carrier(name, iata, icao) values ('Tyrolean Airways Tiroler Luftfahrt GmbH', 'VO', 'TYR');
insert into carrier(name, iata, icao) values ('UNI Airways Corporation', 'B7', 'UIA');
insert into carrier(name, iata, icao) values ('UPS', '5X', 'UPS');
insert into carrier(name, iata, icao) values ('US Airways, Inc.', 'US', 'USA');
insert into carrier(name, iata, icao) values ('USA Jet Airlines, Inc.', 'UJ', 'JUS');
insert into carrier(name, iata, icao) values ('UTair Aviation Joint-Stock Company', 'UT', 'TMN');
insert into carrier(name, iata, icao) values ('Ukraine International Airlines', 'PS', 'AUI');
insert into carrier(name, iata, icao) values ('Ukrainian Mediterranean Airlines Ltd.', 'UF', 'UKM');
insert into carrier(name, iata, icao) values ('United Airlines, Inc.', 'UA', 'UAL');
insert into carrier(name, iata, icao) values ('United Airways Bangladesh Ltd', '4H', '');
insert into carrier(name, iata, icao) values ('United Eagle Airlines Co Ltd', 'EU', '');
insert into carrier(name, iata, icao) values ('Universal Airways, Inc.', 'UV', 'UVA');
insert into carrier(name, iata, icao) values ('Ural Airlines', 'U6', 'SVR');
insert into carrier(name, iata, icao) values ('Utair - Express Limited Company', 'UR', '');
insert into carrier(name, iata, icao) values ('Uzbekistan Havo Yullary -', 'HY', 'UZB');
insert into carrier(name, iata, icao) values ('VIM Airlines', 'NN', 'MOV');
insert into carrier(name, iata, icao) values ('VRG Linhas Aereas S.A.', 'G3', '');
insert into carrier(name, iata, icao) values ('Valuair Ltd.', 'VF', '');
insert into carrier(name, iata, icao) values ('Van Air Europe, a.s.', '6Z', '');
insert into carrier(name, iata, icao) values ('Varig Logistica S/A', 'LC', 'VLO');
insert into carrier(name, iata, icao) values ('Vensecar Internacional C.A.', 'V4', 'VEC');
insert into carrier(name, iata, icao) values ('Vietnam Air Service Company', '0V', '');
insert into carrier(name, iata, icao) values ('Vietnam Airlines Corporation', 'VN', 'HVN');
insert into carrier(name, iata, icao) values ('Vip Air, spol. S.r.o', 'V5', 'VPA');
insert into carrier(name, iata, icao) values ('Virgin America Inc.', 'VX', 'VRD');
insert into carrier(name, iata, icao) values ('Virgin Atlantic Airways Limited', 'VS', 'VIR');
insert into carrier(name, iata, icao) values ('Virgin Blue Airlines Pty Ltd', 'DJ', 'VOZ');
insert into carrier(name, iata, icao) values ('Virgin Blue International Airlines', 'VA', 'VAU');
insert into carrier(name, iata, icao) values ('Virgin Nigeria Airways', 'VK', 'VGN');
insert into carrier(name, iata, icao) values ('Viva Macau Limited', 'ZG', '');
insert into carrier(name, iata, icao) values ('Vladivostok Air JSC', 'XF', 'VLK');
insert into carrier(name, iata, icao) values ('Volga-Dnepr Airline Joint Stock', 'VI', 'VDA');
insert into carrier(name, iata, icao) values ('Voyager Airlines Ltd', 'V6', 'VOG');
insert into carrier(name, iata, icao) values ('Webjet Linhas Aereas S/A', 'WH', 'WEB');
insert into carrier(name, iata, icao) values ('West Coast Air', '8O', '');
insert into carrier(name, iata, icao) values ('WestJet', 'WS', 'WJA');
insert into carrier(name, iata, icao) values ('White Airways S.A.', '', 'WHT');
insert into carrier(name, iata, icao) values ('Wideroe''s Flyveselskap A.S.', 'WF', 'WIF');
insert into carrier(name, iata, icao) values ('Wind Rose Aviation Company', '7W', '');
insert into carrier(name, iata, icao) values ('Windward Islands Airways Int''l  N.V.', 'WM', 'WIA');
insert into carrier(name, iata, icao) values ('Wings Air', 'IW', '');
insert into carrier(name, iata, icao) values ('Woodgate Executive Air Charter UK Ltd.', '3W', '');
insert into carrier(name, iata, icao) values ('World Airways', 'WO', 'WOA');
insert into carrier(name, iata, icao) values ('Worldwide Jet Charter L.L.C.', 'T8', 'WWI');
insert into carrier(name, iata, icao) values ('XL Airways France', 'SE', 'XLF');
insert into carrier(name, iata, icao) values ('Xiamen Airlines', 'MF', 'CXA');
insert into carrier(name, iata, icao) values ('Yamal Airlines', 'YC', 'LLM');
insert into carrier(name, iata, icao) values ('Yangtze River Express Airlines Company', 'Y8', 'YZR');
insert into carrier(name, iata, icao) values ('Yemenia - Yemen Airways', 'IY', 'IYE');
insert into carrier(name, iata, icao) values ('Zambezi Airlines', 'ZJ', 'ZMA');
insert into carrier(name, iata, icao) values ('Zambia Skyways Ltd.', 'K8', '');
insert into carrier(name, iata, icao) values ('Zambian Airways', 'Q3', 'MAZ');
insert into carrier(name, iata, icao) values ('Zoom Airlines Inc.', 'Z4', 'OOM');
insert into carrier(name, iata, icao) values ('Zoom Airways Limited', '3Z', 'ZAW');
insert into carrier(name, iata, icao) values ('joint stock company Avion Express', 'X9', 'NVD');
insert into carrier(name, iata, icao) values ('Unknown Canadian Airline', '*c', '99c');
insert into carrier(name, iata, icao) values ('Unknown Foreign Airline', '*f', '99f');
insert into carrier(name, iata, icao) values ('Unknown US Airline', '*u', '99u');
insert into carrier(name, iata, icao) values ('Aircraft Under Their Own Power', '*o', '99o');
