SET NAMES utf8mb4;
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Afghanistan', 'AF', 'AFG', '004', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Åland Islands', 'AX', 'ALA', '248', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Albania', 'AL', 'ALB', '008', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Algeria', 'DZ', 'DZA', '012', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('American Samoa', 'AS', 'ASM', '016', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Andorra', 'AD', 'AND', '020', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Angola', 'AO', 'AGO', '024', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Anguilla', 'AI', 'AIA', '660', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Antarctica', 'AQ', 'ATA', '010', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Antigua and Barbuda', 'AG', 'ATG', '028', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Argentina', 'AR', 'ARG', '032', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Armenia', 'AM', 'ARM', '051', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Aruba', 'AW', 'ABW', '533', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Australia', 'AU', 'AUS', '036', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Austria', 'AT', 'AUT', '040', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Azerbaijan', 'AZ', 'AZE', '031', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bahamas', 'BS', 'BHS', '044', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bahrain', 'BH', 'BHR', '048', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bangladesh', 'BD', 'BGD', '050', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Barbados', 'BB', 'BRB', '052', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Belarus', 'BY', 'BLR', '112', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Belgium', 'BE', 'BEL', '056', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Belize', 'BZ', 'BLZ', '084', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Benin', 'BJ', 'BEN', '204', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bermuda', 'BM', 'BMU', '060', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bhutan', 'BT', 'BTN', '064', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bolivia', 'BO', 'BOL', '068', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '535', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bosnia and Herzegovina', 'BA', 'BIH', '070', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Botswana', 'BW', 'BWA', '072', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bouvet Island', 'BV', 'BVT', '074', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Brazil', 'BR', 'BRA', '076', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('British Virgin Islands', 'VG', 'VGB', '092', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('British Indian Ocean Territory', 'IO', 'IOT', '086', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Brunei Darussalam', 'BN', 'BRN', '096', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Bulgaria', 'BG', 'BGR', '100', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Burkina Faso', 'BF', 'BFA', '854', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Burundi', 'BI', 'BDI', '108', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cambodia', 'KH', 'KHM', '116', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cameroon', 'CM', 'CMR', '120', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Canada', 'CA', 'CAN', '124', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cape Verde', 'CV', 'CPV', '132', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cayman Islands', 'KY', 'CYM', '136', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Central African Republic', 'CF', 'CAF', '140', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Chad', 'TD', 'TCD', '148', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Chile', 'CL', 'CHL', '152', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('China', 'CN', 'CHN', '156', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Hong Kong', 'HK', 'HKG', '344', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Macau', 'MO', 'MAC', '446', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Christmas Island', 'CX', 'CXR', '162', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cocos (Keeling) Islands', 'CC', 'CCK', '166', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Colombia', 'CO', 'COL', '170', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Comoros', 'KM', 'COM', '174', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Republic of the Congo', 'CG', 'COG', '178', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Democratic Republic of the Congo', 'CD', 'COD', '180', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cook Islands', 'CK', 'COK', '184', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Costa Rica', 'CR', 'CRI', '188', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ("Côte d'Ivoire", 'CI', 'CIV', '384', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Croatia', 'HR', 'HRV', '191', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cuba', 'CU', 'CUB', '192', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Curaçao', 'CW', 'CUW', '531', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Cyprus', 'CY', 'CYP', '196', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Czech Republic', 'CZ', 'CZE', '203', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Denmark', 'DK', 'DNK', '208', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Djibouti', 'DJ', 'DJI', '262', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Dominica', 'DM', 'DMA', '212', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Dominican Republic', 'DO', 'DOM', '214', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Ecuador', 'EC', 'ECU', '218', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Egypt', 'EG', 'EGY', '818', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('El Salvador', 'SV', 'SLV', '222', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Equatorial Guinea', 'GQ', 'GNQ', '226', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Eritrea', 'ER', 'ERI', '232', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Estonia', 'EE', 'EST', '233', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Ethiopia', 'ET', 'ETH', '231', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Falkland Islands', 'FK', 'FLK', '238', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Faroe Islands', 'FO', 'FRO', '234', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Fiji', 'FJ', 'FJI', '242', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Finland', 'FI', 'FIN', '246', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('France', 'FR', 'FRA', '250', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('French Guiana', 'GF', 'GUF', '254', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('French Polynesia', 'PF', 'PYF', '258', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('French Southern Territories', 'TF', 'ATF', '260', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Gabon', 'GA', 'GAB', '266', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Gambia', 'GM', 'GMB', '270', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Georgia', 'GE', 'GEO', '268', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Germany', 'DE', 'DEU', '276', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Ghana', 'GH', 'GHA', '288', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Gibraltar', 'GI', 'GIB', '292', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Greece', 'GR', 'GRC', '300', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Greenland', 'GL', 'GRL', '304', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Grenada', 'GD', 'GRD', '308', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Guadeloupe', 'GP', 'GLP', '312', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Guam', 'GU', 'GUM', '316', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Guatemala', 'GT', 'GTM', '320', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Guernsey', 'GG', 'GGY', '831', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Guinea', 'GN', 'GIN', '324', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Guinea-Bissau', 'GW', 'GNB', '624', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Guyana', 'GY', 'GUY', '328', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Haiti', 'HT', 'HTI', '332', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Heard Island and Mcdonald Islands', 'HM', 'HMD', '334', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Holy See (Vatican City State)', 'VA', 'VAT', '336', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Honduras', 'HN', 'HND', '340', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Hungary', 'HU', 'HUN', '348', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Iceland', 'IS', 'ISL', '352', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('India', 'IN', 'IND', '356', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Indonesia', 'ID', 'IDN', '360', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Iran', 'IR', 'IRN', '364', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Iraq', 'IQ', 'IRQ', '368', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Ireland', 'IE', 'IRL', '372', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Isle of Man', 'IM', 'IMN', '833', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Israel', 'IL', 'ISR', '376', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Italy', 'IT', 'ITA', '380', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Jamaica', 'JM', 'JAM', '388', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Japan', 'JP', 'JPN', '392', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Jersey', 'JE', 'JEY', '832', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Jordan', 'JO', 'JOR', '400', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Kazakhstan', 'KZ', 'KAZ', '398', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Kenya', 'KE', 'KEN', '404', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Kiribati', 'KI', 'KIR', '296', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('North Korea', 'KP', 'PRK', '408', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('South Korea', 'KR', 'KOR', '410', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Kuwait', 'KW', 'KWT', '414', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Kyrgyzstan', 'KG', 'KGZ', '417', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Laos', 'LA', 'LAO', '418', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Latvia', 'LV', 'LVA', '428', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Lebanon', 'LB', 'LBN', '422', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Lesotho', 'LS', 'LSO', '426', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Liberia', 'LR', 'LBR', '430', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Libya', 'LY', 'LBY', '434', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Liechtenstein', 'LI', 'LIE', '438', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Lithuania', 'LT', 'LTU', '440', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Luxembourg', 'LU', 'LUX', '442', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Macedonia', 'MK', 'MKD', '807', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Madagascar', 'MG', 'MDG', '450', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Malawi', 'MW', 'MWI', '454', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Malaysia', 'MY', 'MYS', '458', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Maldives', 'MV', 'MDV', '462', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Mali', 'ML', 'MLI', '466', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Malta', 'MT', 'MLT', '470', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Marshall Islands', 'MH', 'MHL', '584', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Martinique', 'MQ', 'MTQ', '474', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Mauritania', 'MR', 'MRT', '478', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Mauritius', 'MU', 'MUS', '480', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Mayotte', 'YT', 'MYT', '175', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Mexico', 'MX', 'MEX', '484', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Micronesia', 'FM', 'FSM', '583', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Moldova', 'MD', 'MDA', '498', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Monaco', 'MC', 'MCO', '492', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Mongolia', 'MN', 'MNG', '496', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Montenegro', 'ME', 'MNE', '499', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Montserrat', 'MS', 'MSR', '500', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Morocco', 'MA', 'MAR', '504', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Mozambique', 'MZ', 'MOZ', '508', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Myanmar', 'MM', 'MMR', '104', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Namibia', 'NA', 'NAM', '516', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Nauru', 'NR', 'NRU', '520', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Nepal', 'NP', 'NPL', '524', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Netherlands', 'NL', 'NLD', '528', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Netherlands Antilles', 'AN', 'ANT', '530', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('New Caledonia', 'NC', 'NCL', '540', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('New Zealand', 'NZ', 'NZL', '554', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Nicaragua', 'NI', 'NIC', '558', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Niger', 'NE', 'NER', '562', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Nigeria', 'NG', 'NGA', '566', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Niue', 'NU', 'NIU', '570', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Norfolk Island', 'NF', 'NFK', '574', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Northern Mariana Islands', 'MP', 'MNP', '580', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Norway', 'NO', 'NOR', '578', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Oman', 'OM', 'OMN', '512', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Pakistan', 'PK', 'PAK', '586', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Palau', 'PW', 'PLW', '585', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Palestine', 'PS', 'PSE', '275', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Panama', 'PA', 'PAN', '591', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Papua New Guinea', 'PG', 'PNG', '598', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Paraguay', 'PY', 'PRY', '600', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Peru', 'PE', 'PER', '604', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Philippines', 'PH', 'PHL', '608', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Pitcairn', 'PN', 'PCN', '612', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Poland', 'PL', 'POL', '616', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Portugal', 'PT', 'PRT', '620', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Puerto Rico', 'PR', 'PRI', '630', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Qatar', 'QA', 'QAT', '634', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Réunion', 'RE', 'REU', '638', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Romania', 'RO', 'ROU', '642', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Russia', 'RU', 'RUS', '643', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Rwanda', 'RW', 'RWA', '646', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saint-Barthélemy', 'BL', 'BLM', '652', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saint Helena', 'SH', 'SHN', '654', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saint Kitts and Nevis', 'KN', 'KNA', '659', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saint Lucia', 'LC', 'LCA', '662', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saint-Martin', 'MF', 'MAF', '663', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saint Pierre and Miquelon', 'PM', 'SPM', '666', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saint Vincent and the Grenadines', 'VC', 'VCT', '670', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Samoa', 'WS', 'WSM', '882', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('San Marino', 'SM', 'SMR', '674', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Sao Tome and Principe', 'ST', 'STP', '678', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Saudi Arabia', 'SA', 'SAU', '682', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Senegal', 'SN', 'SEN', '686', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Serbia', 'RS', 'SRB', '688', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Seychelles', 'SC', 'SYC', '690', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Sierra Leone', 'SL', 'SLE', '694', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Singapore', 'SG', 'SGP', '702', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Slovakia', 'SK', 'SVK', '703', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Slovenia', 'SI', 'SVN', '705', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Solomon Islands', 'SB', 'SLB', '090', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Somalia', 'SO', 'SOM', '706', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('South Africa', 'ZA', 'ZAF', '710', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('South Sudan', 'SS', 'SSD', '728', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Spain', 'ES', 'ESP', '724', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Sri Lanka', 'LK', 'LKA', '144', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Sint Maarten', 'SW', 'SXM', '534', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Sudan', 'SD', 'SDN', '736', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Suriname ', 'SR', 'SUR', '740', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Svalbard and Jan Mayen Islands', 'SJ', 'SJM', '744', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Swaziland', 'SZ', 'SWZ', '748', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Sweden', 'SE', 'SWE', '752', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Switzerland', 'CH', 'CHE', '756', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Syria', 'SY', 'SYR', '760', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Taiwan', 'TW', 'TWN', '158', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Tajikistan', 'TJ', 'TJK', '762', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Tanzania', 'TZ', 'TZA', '834', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Thailand', 'TH', 'THA', '764', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Timor-Leste', 'TL', 'TLS', '626', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Togo', 'TG', 'TGO', '768', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Tokelau', 'TK', 'TKL', '772', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Tonga', 'TO', 'TON', '776', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Trinidad and Tobago', 'TT', 'TTO', '780', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Tunisia', 'TN', 'TUN', '788', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Turkey', 'TR', 'TUR', '792', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Turkmenistan', 'TM', 'TKM', '795', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Turks and Caicos Islands', 'TC', 'TCA', '796', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Tuvalu', 'TV', 'TUV', '798', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Uganda', 'UG', 'UGA', '800', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Ukraine', 'UA', 'UKR', '804', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('United Arab Emirates', 'AE', 'ARE', '784', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('United Kingdom', 'GB', 'GBR', '826', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('United States of America', 'US', 'USA', '840', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('United States Minor Outlying Islands', 'UM', 'UMI', '581', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Uruguay', 'UY', 'URY', '858', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Uzbekistan', 'UZ', 'UZB', '860', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Vanuatu', 'VU', 'VUT', '548', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Venezuela', 'VE', 'VEN', '862', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Vietnam', 'VN', 'VNM', '704', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Virgin Islands', 'VI', 'VIR', '850', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Wallis and Futuna Islands', 'WF', 'WLF', '876', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Western Sahara', 'EH', 'ESH', '732', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Yemen', 'YE', 'YEM', '887', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Zambia', 'ZM', 'ZMB', '894', NOW());
insert into country(name, iso2, iso3, iso_numeric, updated_at) values ('Zimbabwe', 'ZW', 'ZWE', '716', NOW());

 -- POPULATE COUNTRYRESTORE TABLE AS EXACT DUPLICATE --
insert into country_restore(id, name, iso2, iso3, iso_numeric) select id, name, iso2, iso3, iso_numeric from country;

-- SET ORIGINID ON THE INITIAL RECORDS IN THE COUNTRY TABLE ONLY
update country set originId = id;

