insert into country(name, iso2, iso3, iso_numeric) values ('Afghanistan', 'AF', 'AFG', '004');
insert into country(name, iso2, iso3, iso_numeric) values ('Åland Islands', 'AX', 'ALA', '248');
insert into country(name, iso2, iso3, iso_numeric) values ('Albania', 'AL', 'ALB', '008');
insert into country(name, iso2, iso3, iso_numeric) values ('Algeria', 'DZ', 'DZA', '012');
insert into country(name, iso2, iso3, iso_numeric) values ('American Samoa', 'AS', 'ASM', '016');
insert into country(name, iso2, iso3, iso_numeric) values ('Andorra', 'AD', 'AND', '020');
insert into country(name, iso2, iso3, iso_numeric) values ('Angola', 'AO', 'AGO', '024');
insert into country(name, iso2, iso3, iso_numeric) values ('Anguilla', 'AI', 'AIA', '660');
insert into country(name, iso2, iso3, iso_numeric) values ('Antarctica', 'AQ', 'ATA', '010');
insert into country(name, iso2, iso3, iso_numeric) values ('Antigua and Barbuda', 'AG', 'ATG', '028');
insert into country(name, iso2, iso3, iso_numeric) values ('Argentina', 'AR', 'ARG', '032');
insert into country(name, iso2, iso3, iso_numeric) values ('Armenia', 'AM', 'ARM', '051');
insert into country(name, iso2, iso3, iso_numeric) values ('Aruba', 'AW', 'ABW', '533');
insert into country(name, iso2, iso3, iso_numeric) values ('Australia', 'AU', 'AUS', '036');
insert into country(name, iso2, iso3, iso_numeric) values ('Austria', 'AT', 'AUT', '040');
insert into country(name, iso2, iso3, iso_numeric) values ('Azerbaijan', 'AZ', 'AZE', '031');
insert into country(name, iso2, iso3, iso_numeric) values ('Bahamas', 'BS', 'BHS', '044');
insert into country(name, iso2, iso3, iso_numeric) values ('Bahrain', 'BH', 'BHR', '048');
insert into country(name, iso2, iso3, iso_numeric) values ('Bangladesh', 'BD', 'BGD', '050');
insert into country(name, iso2, iso3, iso_numeric) values ('Barbados', 'BB', 'BRB', '052');
insert into country(name, iso2, iso3, iso_numeric) values ('Belarus', 'BY', 'BLR', '112');
insert into country(name, iso2, iso3, iso_numeric) values ('Belgium', 'BE', 'BEL', '056');
insert into country(name, iso2, iso3, iso_numeric) values ('Belize', 'BZ', 'BLZ', '084');
insert into country(name, iso2, iso3, iso_numeric) values ('Benin', 'BJ', 'BEN', '204');
insert into country(name, iso2, iso3, iso_numeric) values ('Bermuda', 'BM', 'BMU', '060');
insert into country(name, iso2, iso3, iso_numeric) values ('Bhutan', 'BT', 'BTN', '064');
insert into country(name, iso2, iso3, iso_numeric) values ('Bolivia', 'BO', 'BOL', '068');
insert into country(name, iso2, iso3, iso_numeric) values ('Bosnia and Herzegovina', 'BA', 'BIH', '070');
insert into country(name, iso2, iso3, iso_numeric) values ('Botswana', 'BW', 'BWA', '072');
insert into country(name, iso2, iso3, iso_numeric) values ('Bouvet Island', 'BV', 'BVT', '074');
insert into country(name, iso2, iso3, iso_numeric) values ('Brazil', 'BR', 'BRA', '076');
insert into country(name, iso2, iso3, iso_numeric) values ('British Virgin Islands', 'VG', 'VGB', '092');
insert into country(name, iso2, iso3, iso_numeric) values ('British Indian Ocean Territory', 'IO', 'IOT', '086');
insert into country(name, iso2, iso3, iso_numeric) values ('Brunei Darussalam', 'BN', 'BRN', '096');
insert into country(name, iso2, iso3, iso_numeric) values ('Bulgaria', 'BG', 'BGR', '100');
insert into country(name, iso2, iso3, iso_numeric) values ('Burkina Faso', 'BF', 'BFA', '854');
insert into country(name, iso2, iso3, iso_numeric) values ('Burundi', 'BI', 'BDI', '108');
insert into country(name, iso2, iso3, iso_numeric) values ('Cambodia', 'KH', 'KHM', '116');
insert into country(name, iso2, iso3, iso_numeric) values ('Cameroon', 'CM', 'CMR', '120');
insert into country(name, iso2, iso3, iso_numeric) values ('Canada', 'CA', 'CAN', '124');
insert into country(name, iso2, iso3, iso_numeric) values ('Cape Verde', 'CV', 'CPV', '132');
insert into country(name, iso2, iso3, iso_numeric) values ('Cayman Islands', 'KY', 'CYM', '136');
insert into country(name, iso2, iso3, iso_numeric) values ('Central African Republic', 'CF', 'CAF', '140');
insert into country(name, iso2, iso3, iso_numeric) values ('Chad', 'TD', 'TCD', '148');
insert into country(name, iso2, iso3, iso_numeric) values ('Chile', 'CL', 'CHL', '152');
insert into country(name, iso2, iso3, iso_numeric) values ('China', 'CN', 'CHN', '156');
insert into country(name, iso2, iso3, iso_numeric) values ('Hong Kong, Special Administrative Region of China', 'HK', 'HKG', '344');
insert into country(name, iso2, iso3, iso_numeric) values ('Macao, Special Administrative Region of China', 'MO', 'MAC', '446');
insert into country(name, iso2, iso3, iso_numeric) values ('Christmas Island', 'CX', 'CXR', '162');
insert into country(name, iso2, iso3, iso_numeric) values ('Cocos (Keeling) Islands', 'CC', 'CCK', '166');
insert into country(name, iso2, iso3, iso_numeric) values ('Colombia', 'CO', 'COL', '170');
insert into country(name, iso2, iso3, iso_numeric) values ('Comoros', 'KM', 'COM', '174');
insert into country(name, iso2, iso3, iso_numeric) values ('Congo (Brazzaville)', 'CG', 'COG', '178');
insert into country(name, iso2, iso3, iso_numeric) values ('Congo, Democratic Republic of the', 'CD', 'COD', '180');
insert into country(name, iso2, iso3, iso_numeric) values ('Cook Islands', 'CK', 'COK', '184');
insert into country(name, iso2, iso3, iso_numeric) values ('Costa Rica', 'CR', 'CRI', '188');
insert into country(name, iso2, iso3, iso_numeric) values ('Côte d\'Ivoire', 'CI', 'CIV', '384');
insert into country(name, iso2, iso3, iso_numeric) values ('Croatia', 'HR', 'HRV', '191');
insert into country(name, iso2, iso3, iso_numeric) values ('Cuba', 'CU', 'CUB', '192');
insert into country(name, iso2, iso3, iso_numeric) values ('Cyprus', 'CY', 'CYP', '196');
insert into country(name, iso2, iso3, iso_numeric) values ('Czech Republic', 'CZ', 'CZE', '203');
insert into country(name, iso2, iso3, iso_numeric) values ('Denmark', 'DK', 'DNK', '208');
insert into country(name, iso2, iso3, iso_numeric) values ('Djibouti', 'DJ', 'DJI', '262');
insert into country(name, iso2, iso3, iso_numeric) values ('Dominica', 'DM', 'DMA', '212');
insert into country(name, iso2, iso3, iso_numeric) values ('Dominican Republic', 'DO', 'DOM', '214');
insert into country(name, iso2, iso3, iso_numeric) values ('Ecuador', 'EC', 'ECU', '218');
insert into country(name, iso2, iso3, iso_numeric) values ('Egypt', 'EG', 'EGY', '818');
insert into country(name, iso2, iso3, iso_numeric) values ('El Salvador', 'SV', 'SLV', '222');
insert into country(name, iso2, iso3, iso_numeric) values ('Equatorial Guinea', 'GQ', 'GNQ', '226');
insert into country(name, iso2, iso3, iso_numeric) values ('Eritrea', 'ER', 'ERI', '232');
insert into country(name, iso2, iso3, iso_numeric) values ('Estonia', 'EE', 'EST', '233');
insert into country(name, iso2, iso3, iso_numeric) values ('Ethiopia', 'ET', 'ETH', '231');
insert into country(name, iso2, iso3, iso_numeric) values ('Falkland Islands (Malvinas)', 'FK', 'FLK', '238');
insert into country(name, iso2, iso3, iso_numeric) values ('Faroe Islands', 'FO', 'FRO', '234');
insert into country(name, iso2, iso3, iso_numeric) values ('Fiji', 'FJ', 'FJI', '242');
insert into country(name, iso2, iso3, iso_numeric) values ('Finland', 'FI', 'FIN', '246');
insert into country(name, iso2, iso3, iso_numeric) values ('France', 'FR', 'FRA', '250');
insert into country(name, iso2, iso3, iso_numeric) values ('French Guiana', 'GF', 'GUF', '254');
insert into country(name, iso2, iso3, iso_numeric) values ('French Polynesia', 'PF', 'PYF', '258');
insert into country(name, iso2, iso3, iso_numeric) values ('French Southern Territories', 'TF', 'ATF', '260');
insert into country(name, iso2, iso3, iso_numeric) values ('Gabon', 'GA', 'GAB', '266');
insert into country(name, iso2, iso3, iso_numeric) values ('Gambia', 'GM', 'GMB', '270');
insert into country(name, iso2, iso3, iso_numeric) values ('Georgia', 'GE', 'GEO', '268');
insert into country(name, iso2, iso3, iso_numeric) values ('Germany', 'DE', 'DEU', '276');
insert into country(name, iso2, iso3, iso_numeric) values ('Ghana', 'GH', 'GHA', '288');
insert into country(name, iso2, iso3, iso_numeric) values ('Gibraltar', 'GI', 'GIB', '292');
insert into country(name, iso2, iso3, iso_numeric) values ('Greece', 'GR', 'GRC', '300');
insert into country(name, iso2, iso3, iso_numeric) values ('Greenland', 'GL', 'GRL', '304');
insert into country(name, iso2, iso3, iso_numeric) values ('Grenada', 'GD', 'GRD', '308');
insert into country(name, iso2, iso3, iso_numeric) values ('Guadeloupe', 'GP', 'GLP', '312');
insert into country(name, iso2, iso3, iso_numeric) values ('Guam', 'GU', 'GUM', '316');
insert into country(name, iso2, iso3, iso_numeric) values ('Guatemala', 'GT', 'GTM', '320');
insert into country(name, iso2, iso3, iso_numeric) values ('Guernsey', 'GG', 'GGY', '831');
insert into country(name, iso2, iso3, iso_numeric) values ('Guinea', 'GN', 'GIN', '324');
insert into country(name, iso2, iso3, iso_numeric) values ('Guinea-Bissau', 'GW', 'GNB', '624');
insert into country(name, iso2, iso3, iso_numeric) values ('Guyana', 'GY', 'GUY', '328');
insert into country(name, iso2, iso3, iso_numeric) values ('Haiti', 'HT', 'HTI', '332');
insert into country(name, iso2, iso3, iso_numeric) values ('Heard Island and Mcdonald Islands', 'HM', 'HMD', '334');
insert into country(name, iso2, iso3, iso_numeric) values ('Holy See (Vatican City State)', 'VA', 'VAT', '336');
insert into country(name, iso2, iso3, iso_numeric) values ('Honduras', 'HN', 'HND', '340');
insert into country(name, iso2, iso3, iso_numeric) values ('Hungary', 'HU', 'HUN', '348');
insert into country(name, iso2, iso3, iso_numeric) values ('Iceland', 'IS', 'ISL', '352');
insert into country(name, iso2, iso3, iso_numeric) values ('India', 'IN', 'IND', '356');
insert into country(name, iso2, iso3, iso_numeric) values ('Indonesia', 'ID', 'IDN', '360');
insert into country(name, iso2, iso3, iso_numeric) values ('Iran, Islamic Republic of', 'IR', 'IRN', '364');
insert into country(name, iso2, iso3, iso_numeric) values ('Iraq', 'IQ', 'IRQ', '368');
insert into country(name, iso2, iso3, iso_numeric) values ('Ireland', 'IE', 'IRL', '372');
insert into country(name, iso2, iso3, iso_numeric) values ('Isle of Man', 'IM', 'IMN', '833');
insert into country(name, iso2, iso3, iso_numeric) values ('Israel', 'IL', 'ISR', '376');
insert into country(name, iso2, iso3, iso_numeric) values ('Italy', 'IT', 'ITA', '380');
insert into country(name, iso2, iso3, iso_numeric) values ('Jamaica', 'JM', 'JAM', '388');
insert into country(name, iso2, iso3, iso_numeric) values ('Japan', 'JP', 'JPN', '392');
insert into country(name, iso2, iso3, iso_numeric) values ('Jersey', 'JE', 'JEY', '832');
insert into country(name, iso2, iso3, iso_numeric) values ('Jordan', 'JO', 'JOR', '400');
insert into country(name, iso2, iso3, iso_numeric) values ('Kazakhstan', 'KZ', 'KAZ', '398');
insert into country(name, iso2, iso3, iso_numeric) values ('Kenya', 'KE', 'KEN', '404');
insert into country(name, iso2, iso3, iso_numeric) values ('Kiribati', 'KI', 'KIR', '296');
insert into country(name, iso2, iso3, iso_numeric) values ('Korea, Democratic People''s Republic of', 'KP', 'PRK', '408');
insert into country(name, iso2, iso3, iso_numeric) values ('Korea, Republic of', 'KR', 'KOR', '410');
insert into country(name, iso2, iso3, iso_numeric) values ('Kuwait', 'KW', 'KWT', '414');
insert into country(name, iso2, iso3, iso_numeric) values ('Kyrgyzstan', 'KG', 'KGZ', '417');
insert into country(name, iso2, iso3, iso_numeric) values ('Lao PDR', 'LA', 'LAO', '418');
insert into country(name, iso2, iso3, iso_numeric) values ('Latvia', 'LV', 'LVA', '428');
insert into country(name, iso2, iso3, iso_numeric) values ('Lebanon', 'LB', 'LBN', '422');
insert into country(name, iso2, iso3, iso_numeric) values ('Lesotho', 'LS', 'LSO', '426');
insert into country(name, iso2, iso3, iso_numeric) values ('Liberia', 'LR', 'LBR', '430');
insert into country(name, iso2, iso3, iso_numeric) values ('Libya', 'LY', 'LBY', '434');
insert into country(name, iso2, iso3, iso_numeric) values ('Liechtenstein', 'LI', 'LIE', '438');
insert into country(name, iso2, iso3, iso_numeric) values ('Lithuania', 'LT', 'LTU', '440');
insert into country(name, iso2, iso3, iso_numeric) values ('Luxembourg', 'LU', 'LUX', '442');
insert into country(name, iso2, iso3, iso_numeric) values ('Macedonia, Republic of', 'MK', 'MKD', '807');
insert into country(name, iso2, iso3, iso_numeric) values ('Madagascar', 'MG', 'MDG', '450');
insert into country(name, iso2, iso3, iso_numeric) values ('Malawi', 'MW', 'MWI', '454');
insert into country(name, iso2, iso3, iso_numeric) values ('Malaysia', 'MY', 'MYS', '458');
insert into country(name, iso2, iso3, iso_numeric) values ('Maldives', 'MV', 'MDV', '462');
insert into country(name, iso2, iso3, iso_numeric) values ('Mali', 'ML', 'MLI', '466');
insert into country(name, iso2, iso3, iso_numeric) values ('Malta', 'MT', 'MLT', '470');
insert into country(name, iso2, iso3, iso_numeric) values ('Marshall Islands', 'MH', 'MHL', '584');
insert into country(name, iso2, iso3, iso_numeric) values ('Martinique', 'MQ', 'MTQ', '474');
insert into country(name, iso2, iso3, iso_numeric) values ('Mauritania', 'MR', 'MRT', '478');
insert into country(name, iso2, iso3, iso_numeric) values ('Mauritius', 'MU', 'MUS', '480');
insert into country(name, iso2, iso3, iso_numeric) values ('Mayotte', 'YT', 'MYT', '175');
insert into country(name, iso2, iso3, iso_numeric) values ('Mexico', 'MX', 'MEX', '484');
insert into country(name, iso2, iso3, iso_numeric) values ('Micronesia, Federated States of', 'FM', 'FSM', '583');
insert into country(name, iso2, iso3, iso_numeric) values ('Moldova', 'MD', 'MDA', '498');
insert into country(name, iso2, iso3, iso_numeric) values ('Monaco', 'MC', 'MCO', '492');
insert into country(name, iso2, iso3, iso_numeric) values ('Mongolia', 'MN', 'MNG', '496');
insert into country(name, iso2, iso3, iso_numeric) values ('Montenegro', 'ME', 'MNE', '499');
insert into country(name, iso2, iso3, iso_numeric) values ('Montserrat', 'MS', 'MSR', '500');
insert into country(name, iso2, iso3, iso_numeric) values ('Morocco', 'MA', 'MAR', '504');
insert into country(name, iso2, iso3, iso_numeric) values ('Mozambique', 'MZ', 'MOZ', '508');
insert into country(name, iso2, iso3, iso_numeric) values ('Myanmar', 'MM', 'MMR', '104');
insert into country(name, iso2, iso3, iso_numeric) values ('Namibia', 'NA', 'NAM', '516');
insert into country(name, iso2, iso3, iso_numeric) values ('Nauru', 'NR', 'NRU', '520');
insert into country(name, iso2, iso3, iso_numeric) values ('Nepal', 'NP', 'NPL', '524');
insert into country(name, iso2, iso3, iso_numeric) values ('Netherlands', 'NL', 'NLD', '528');
insert into country(name, iso2, iso3, iso_numeric) values ('Netherlands Antilles', 'AN', 'ANT', '530');
insert into country(name, iso2, iso3, iso_numeric) values ('New Caledonia', 'NC', 'NCL', '540');
insert into country(name, iso2, iso3, iso_numeric) values ('New Zealand', 'NZ', 'NZL', '554');
insert into country(name, iso2, iso3, iso_numeric) values ('Nicaragua', 'NI', 'NIC', '558');
insert into country(name, iso2, iso3, iso_numeric) values ('Niger', 'NE', 'NER', '562');
insert into country(name, iso2, iso3, iso_numeric) values ('Nigeria', 'NG', 'NGA', '566');
insert into country(name, iso2, iso3, iso_numeric) values ('Niue', 'NU', 'NIU', '570');
insert into country(name, iso2, iso3, iso_numeric) values ('Norfolk Island', 'NF', 'NFK', '574');
insert into country(name, iso2, iso3, iso_numeric) values ('Northern Mariana Islands', 'MP', 'MNP', '580');
insert into country(name, iso2, iso3, iso_numeric) values ('Norway', 'NO', 'NOR', '578');
insert into country(name, iso2, iso3, iso_numeric) values ('Oman', 'OM', 'OMN', '512');
insert into country(name, iso2, iso3, iso_numeric) values ('Pakistan', 'PK', 'PAK', '586');
insert into country(name, iso2, iso3, iso_numeric) values ('Palau', 'PW', 'PLW', '585');
insert into country(name, iso2, iso3, iso_numeric) values ('Palestinian Territory, Occupied', 'PS', 'PSE', '275');
insert into country(name, iso2, iso3, iso_numeric) values ('Panama', 'PA', 'PAN', '591');
insert into country(name, iso2, iso3, iso_numeric) values ('Papua New Guinea', 'PG', 'PNG', '598');
insert into country(name, iso2, iso3, iso_numeric) values ('Paraguay', 'PY', 'PRY', '600');
insert into country(name, iso2, iso3, iso_numeric) values ('Peru', 'PE', 'PER', '604');
insert into country(name, iso2, iso3, iso_numeric) values ('Philippines', 'PH', 'PHL', '608');
insert into country(name, iso2, iso3, iso_numeric) values ('Pitcairn', 'PN', 'PCN', '612');
insert into country(name, iso2, iso3, iso_numeric) values ('Poland', 'PL', 'POL', '616');
insert into country(name, iso2, iso3, iso_numeric) values ('Portugal', 'PT', 'PRT', '620');
insert into country(name, iso2, iso3, iso_numeric) values ('Puerto Rico', 'PR', 'PRI', '630');
insert into country(name, iso2, iso3, iso_numeric) values ('Qatar', 'QA', 'QAT', '634');
insert into country(name, iso2, iso3, iso_numeric) values ('Réunion', 'RE', 'REU', '638');
insert into country(name, iso2, iso3, iso_numeric) values ('Romania', 'RO', 'ROU', '642');
insert into country(name, iso2, iso3, iso_numeric) values ('Russian Federation', 'RU', 'RUS', '643');
insert into country(name, iso2, iso3, iso_numeric) values ('Rwanda', 'RW', 'RWA', '646');
insert into country(name, iso2, iso3, iso_numeric) values ('Saint-Barthélemy', 'BL', 'BLM', '652');
insert into country(name, iso2, iso3, iso_numeric) values ('Saint Helena', 'SH', 'SHN', '654');
insert into country(name, iso2, iso3, iso_numeric) values ('Saint Kitts and Nevis', 'KN', 'KNA', '659');
insert into country(name, iso2, iso3, iso_numeric) values ('Saint Lucia', 'LC', 'LCA', '662');
insert into country(name, iso2, iso3, iso_numeric) values ('Saint-Martin (French part)', 'MF', 'MAF', '663');
insert into country(name, iso2, iso3, iso_numeric) values ('Saint Pierre and Miquelon', 'PM', 'SPM', '666');
insert into country(name, iso2, iso3, iso_numeric) values ('Saint Vincent and Grenadines', 'VC', 'VCT', '670');
insert into country(name, iso2, iso3, iso_numeric) values ('Samoa', 'WS', 'WSM', '882');
insert into country(name, iso2, iso3, iso_numeric) values ('San Marino', 'SM', 'SMR', '674');
insert into country(name, iso2, iso3, iso_numeric) values ('Sao Tome and Principe', 'ST', 'STP', '678');
insert into country(name, iso2, iso3, iso_numeric) values ('Saudi Arabia', 'SA', 'SAU', '682');
insert into country(name, iso2, iso3, iso_numeric) values ('Senegal', 'SN', 'SEN', '686');
insert into country(name, iso2, iso3, iso_numeric) values ('Serbia', 'RS', 'SRB', '688');
insert into country(name, iso2, iso3, iso_numeric) values ('Seychelles', 'SC', 'SYC', '690');
insert into country(name, iso2, iso3, iso_numeric) values ('Sierra Leone', 'SL', 'SLE', '694');
insert into country(name, iso2, iso3, iso_numeric) values ('Singapore', 'SG', 'SGP', '702');
insert into country(name, iso2, iso3, iso_numeric) values ('Slovakia', 'SK', 'SVK', '703');
insert into country(name, iso2, iso3, iso_numeric) values ('Slovenia', 'SI', 'SVN', '705');
insert into country(name, iso2, iso3, iso_numeric) values ('Solomon Islands', 'SB', 'SLB', '090');
insert into country(name, iso2, iso3, iso_numeric) values ('Somalia', 'SO', 'SOM', '706');
insert into country(name, iso2, iso3, iso_numeric) values ('South Africa', 'ZA', 'ZAF', '710');
insert into country(name, iso2, iso3, iso_numeric) values ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239');
insert into country(name, iso2, iso3, iso_numeric) values ('South Sudan', 'SS', 'SSD', '728');
insert into country(name, iso2, iso3, iso_numeric) values ('Spain', 'ES', 'ESP', '724');
insert into country(name, iso2, iso3, iso_numeric) values ('Sri Lanka', 'LK', 'LKA', '144');
insert into country(name, iso2, iso3, iso_numeric) values ('Sudan', 'SD', 'SDN', '736');
insert into country(name, iso2, iso3, iso_numeric) values ('Suriname ', 'SR', 'SUR', '740');
insert into country(name, iso2, iso3, iso_numeric) values ('Svalbard and Jan Mayen Islands', 'SJ', 'SJM', '744');
insert into country(name, iso2, iso3, iso_numeric) values ('Swaziland', 'SZ', 'SWZ', '748');
insert into country(name, iso2, iso3, iso_numeric) values ('Sweden', 'SE', 'SWE', '752');
insert into country(name, iso2, iso3, iso_numeric) values ('Switzerland', 'CH', 'CHE', '756');
insert into country(name, iso2, iso3, iso_numeric) values ('Syrian Arab Republic (Syria)', 'SY', 'SYR', '760');
insert into country(name, iso2, iso3, iso_numeric) values ('Taiwan, Republic of China', 'TW', 'TWN', '158');
insert into country(name, iso2, iso3, iso_numeric) values ('Tajikistan', 'TJ', 'TJK', '762');
insert into country(name, iso2, iso3, iso_numeric) values ('Tanzania, United Republic of', 'TZ', 'TZA', '834');
insert into country(name, iso2, iso3, iso_numeric) values ('Thailand', 'TH', 'THA', '764');
insert into country(name, iso2, iso3, iso_numeric) values ('Timor-Leste', 'TL', 'TLS', '626');
insert into country(name, iso2, iso3, iso_numeric) values ('Togo', 'TG', 'TGO', '768');
insert into country(name, iso2, iso3, iso_numeric) values ('Tokelau', 'TK', 'TKL', '772');
insert into country(name, iso2, iso3, iso_numeric) values ('Tonga', 'TO', 'TON', '776');
insert into country(name, iso2, iso3, iso_numeric) values ('Trinidad and Tobago', 'TT', 'TTO', '780');
insert into country(name, iso2, iso3, iso_numeric) values ('Tunisia', 'TN', 'TUN', '788');
insert into country(name, iso2, iso3, iso_numeric) values ('Turkey', 'TR', 'TUR', '792');
insert into country(name, iso2, iso3, iso_numeric) values ('Turkmenistan', 'TM', 'TKM', '795');
insert into country(name, iso2, iso3, iso_numeric) values ('Turks and Caicos Islands', 'TC', 'TCA', '796');
insert into country(name, iso2, iso3, iso_numeric) values ('Tuvalu', 'TV', 'TUV', '798');
insert into country(name, iso2, iso3, iso_numeric) values ('Uganda', 'UG', 'UGA', '800');
insert into country(name, iso2, iso3, iso_numeric) values ('Ukraine', 'UA', 'UKR', '804');
insert into country(name, iso2, iso3, iso_numeric) values ('United Arab Emirates', 'AE', 'ARE', '784');
insert into country(name, iso2, iso3, iso_numeric) values ('United Kingdom', 'GB', 'GBR', '826');
insert into country(name, iso2, iso3, iso_numeric) values ('United States of America', 'US', 'USA', '840');
insert into country(name, iso2, iso3, iso_numeric) values ('United States Minor Outlying Islands', 'UM', 'UMI', '581');
insert into country(name, iso2, iso3, iso_numeric) values ('Uruguay', 'UY', 'URY', '858');
insert into country(name, iso2, iso3, iso_numeric) values ('Uzbekistan', 'UZ', 'UZB', '860');
insert into country(name, iso2, iso3, iso_numeric) values ('Vanuatu', 'VU', 'VUT', '548');
insert into country(name, iso2, iso3, iso_numeric) values ('Venezuela (Bolivarian Republic of)', 'VE', 'VEN', '862');
insert into country(name, iso2, iso3, iso_numeric) values ('Viet Nam', 'VN', 'VNM', '704');
insert into country(name, iso2, iso3, iso_numeric) values ('Virgin Islands, US', 'VI', 'VIR', '850');
insert into country(name, iso2, iso3, iso_numeric) values ('Wallis and Futuna Islands', 'WF', 'WLF', '876');
insert into country(name, iso2, iso3, iso_numeric) values ('Western Sahara', 'EH', 'ESH', '732');
insert into country(name, iso2, iso3, iso_numeric) values ('Yemen', 'YE', 'YEM', '887');
insert into country(name, iso2, iso3, iso_numeric) values ('Zambia', 'ZM', 'ZMB', '894');
insert into country(name, iso2, iso3, iso_numeric) values ('Zimbabwe', 'ZW', 'ZWE', '716');

 -- POPULATE COUNTRYRESTORE TABLE AS EXACT DUPLICATE --
insert into countryRestore (id, name, iso2, iso3, iso_numeric)
select id, name, iso2, iso3, iso_numeric from country;


-- SET ORIGINID ON THE INITIAL RECORDS IN THE COUNTRY TABLE ONLY
update country set originId = id;

